import { useEffect,useRef,useState } from 'react';
import { Panel } from '../../components/UI';
import { useSession } from '../../session';
import { ProvenanceChip } from '../../lib/provenance';
import { ocrRequest,type EngineStatus,type OCRJob,type FileResult,type PlateResult } from './ocrLiveApi';
import { exportJob,jobCSV,parseLabelsCSV } from './export';
import AccuracyPanel,{percent} from './AccuracyPanel';

type Upload={file:File;url:string};
const setup='python -m pip install -r requirements-dev.txt -r pipeline/requirements.txt';
function save(name:string,value:string,type:string){const url=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function UploadCard({upload,expected,disabled,onExpected}:{upload:Upload;expected:string;disabled:boolean;onExpected:(value:string)=>void}){const [duration,setDuration]=useState<number|null>(null);return <div><strong>{upload.file.name}</strong>{upload.file.type.startsWith('video')?<video src={upload.url} muted controls preload="metadata" onLoadedMetadata={e=>setDuration(e.currentTarget.duration)}/>:<img src={upload.url} alt={upload.file.name}/>}<small>{(upload.file.size/1024/1024).toFixed(2)} MB{duration!=null&&` · ${duration.toFixed(2)} seconds`}</small><label>Expected plate (optional)<input disabled={disabled} value={expected} placeholder="DL01AB1234" onChange={e=>onExpected(e.target.value)}/></label><small>Indian standard or BH format. Multi-vehicle videos need track labels after the run.</small></div>;}
function Evidence({upload,plate}:{upload?:Upload;plate:PlateResult}){const video=useRef<HTMLVideoElement>(null),canvas=useRef<HTMLCanvasElement>(null),image=useRef<HTMLImageElement>(null);function draw(){const media=video.current||image.current,c=canvas.current;if(!media||!c)return;const w=video.current?.videoWidth||image.current?.naturalWidth||0,h=video.current?.videoHeight||image.current?.naturalHeight||0;if(!w||!h)return;c.width=w;c.height=h;const ctx=c.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,w,h);if(plate.box&&(!video.current||Math.abs(video.current.currentTime-(plate.time_s||0))<.15)){ctx.strokeStyle='#29f3a5';ctx.lineWidth=Math.max(2,w/300);ctx.strokeRect(plate.box[0],plate.box[1],plate.box[2],plate.box[3]);}}
 useEffect(()=>{if(video.current){video.current.currentTime=plate.time_s||0;}draw();},[plate]);
 if(!upload)return <span>Preview released</span>;return <div className="ocr-evidence"><div>{upload.file.type.startsWith('video')?<video ref={video} src={upload.url} controls muted playsInline preload="metadata" onLoadedMetadata={()=>{if(video.current)video.current.currentTime=plate.time_s||0;}} onSeeked={draw} onTimeUpdate={draw}/>:<img ref={image} src={upload.url} alt="Local upload evidence" onLoad={draw}/>}<canvas ref={canvas} aria-hidden="true"/></div>{plate.time_s!=null&&<button onClick={()=>{if(video.current){video.current.pause();video.current.currentTime=plate.time_s!;}}}>Seek track #{plate.track_id} · {plate.time_s.toFixed(2)}s</button>}</div>;}
export function ResultTable({job,uploads,labels,onLabel}:{job:OCRJob;uploads:Upload[];labels:Record<string,string>;onLabel:(key:string,value:string)=>void}){const [sort,setSort]=useState('file');const rows=job.files.flatMap(file=>[...file.plates,...file.tracks].map(plate=>({file,plate}))).sort((a,b)=>sort==='confidence'?b.plate.vote_confidence-a.plate.vote_confidence:sort==='status'?a.plate.status.localeCompare(b.plate.status):a.file.file.localeCompare(b.file.file));return <><label>Sort results<select value={sort} onChange={e=>setSort(e.target.value)}><option value="file">File</option><option value="confidence">Vote confidence</option><option value="status">Status</option></select></label><div className="table-scroll"><table><thead><tr>{['Evidence','File / track','Raw OCR','Normalised','Voted','Format','Vote confidence / reads','Status','Expected plate','Match / CER','Timing'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(({file:f,plate:p},i)=><tr key={`${f.file}-${i}`}><td><Evidence upload={uploads.find(u=>u.file.name===f.file)} plate={p}/></td><td>{f.file}{p.track_id!=null&&` #${p.track_id}`}</td><td>{p.raw||'—'}</td><td>{p.normalised||'—'}</td><td>{p.voted||'—'}</td><td>{p.format_valid?'Valid':'Invalid'} · {p.format}</td><td className={p.vote_confidence>=.8?'confidence-high':'confidence-low'}>{percent(p.vote_confidence)} / {p.n_reads}</td><td>{p.status}<small>{p.reason}</small></td><td><input aria-label={`Expected ${f.file} ${p.track_id??i}`} value={labels[p.label_key||f.file]??p.expected??''} disabled={job.state!=='done'} onChange={e=>onLabel(p.label_key||f.file,e.target.value)}/></td><td>{p.exact_match==null?'Not scored':p.exact_match?'✓':'✕'} / {percent(p.cer)}</td><td>{f.duration_ms?.toFixed(0)} ms<details><summary>Stages</summary>{Object.entries(f.stage_ms||{}).map(([s,t])=><div key={s}>{s}: {t.toFixed(1)} ms</div>)}</details></td></tr>)}</tbody></table></div></>;}
export default function LiveOCRRun(){const {session}=useSession(),[status,setStatus]=useState<EngineStatus|null>(null),[error,setError]=useState(''),[uploads,setUploads]=useState<Upload[]>([]),[labels,setLabels]=useState<Record<string,string>>({}),[mode,setMode]=useState('auto'),[purpose,setPurpose]=useState(''),[reference,setReference]=useState(''),[stride,setStride]=useState(15),[seconds,setSeconds]=useState(60),[job,setJob]=useState<OCRJob|null>(null),[busy,setBusy]=useState(false),[jobId,setJobId]=useState('');const input=useRef<HTMLInputElement>(null),urls=useRef<string[]>([]),activeJob=useRef('');const authorised=!!session&&session.user.role!=='viewer';
 const check=()=>{setError('');ocrRequest<EngineStatus>('status').then(setStatus).catch(e=>{setStatus(null);setError(e.message);});};
 useEffect(()=>{check();return()=>{urls.current.forEach(URL.revokeObjectURL);if(activeJob.current)void ocrRequest(`jobs/${activeJob.current}`,undefined,'DELETE').catch(()=>{});};},[]);
 useEffect(()=>{if(!jobId)return;let disposed=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const value=await ocrRequest<OCRJob>(`jobs/${jobId}`);if(disposed)return;setJob(value);if(['queued','running'].includes(value.state))timer=setTimeout(poll,750);else setBusy(false);}catch(e){if(!disposed){setError((e as Error).message);setStatus(null);setBusy(false);}}};void poll();return()=>{disposed=true;clearTimeout(timer);};},[jobId]);
 function add(files:FileList|File[]){const list=Array.from(files);if(uploads.length+list.length>20){setError('At most 20 files per run');return;}if(new Set([...uploads.map(u=>u.file.name),...list.map(f=>f.name)]).size!==uploads.length+list.length){setError('Rename duplicate filenames before uploading');return;}const next=list.map(file=>{const url=URL.createObjectURL(file);urls.current.push(url);return {file,url};});setUploads(old=>[...old,...next]);}
 async function run(){setBusy(true);setError('');setJob(null);try{const form=new FormData();uploads.forEach(u=>form.append('files[]',u.file));form.set('purpose',[purpose,reference].filter(Boolean).join(' · '));form.set('mode',mode);form.set('stride',String(stride));form.set('max_seconds',String(seconds));form.set('expected',JSON.stringify(Object.fromEntries(Object.entries(labels).filter(([,v])=>v.trim()))));form.set('blind','true');const r=await ocrRequest<{job_id:string}>('jobs',form);activeJob.current=r.job_id;setJobId(r.job_id);}catch(e){setError((e as Error).message);setBusy(false);}}
 async function purge(clear:boolean){try{if(jobId)await ocrRequest(`jobs/${jobId}`,undefined,'DELETE');setBusy(false);setJobId('');activeJob.current='';if(clear){setJob(null);setUploads([]);setLabels({});urls.current.forEach(URL.revokeObjectURL);urls.current=[];}else if(job)setJob({...job,state:'cancelled',files:[]});}catch(e){setError((e as Error).message);}}
 const plates=job?.files.flatMap(f=>[...f.plates,...f.tracks])||[];
 return <Panel title="Run OCR pipeline on your own image or video" className="live-ocr-panel"><div className="padded form-stack"><div className="spread"><ProvenanceChip source="live"/><span role="status">{status?.available?`${status.engine} ${status.engine_version} · ${status.device} · Ready`:'Unavailable'}</span><button onClick={check}>Check engine</button></div>{(!status?.available||error)&&<div role="alert"><p>{error||status?.reasons_if_unavailable.join('; ')||'Checking local OCR service…'}</p><p>Start the local service and sign in with an authenticated Officer or Admin account. Access-profile sessions do not authorise OCR.</p><code>{status?.setup||setup}</code><p><code>python -m uvicorn anpr.api:app --host 127.0.0.1 --port 8000</code> · Set <code>VITE_USE_MOCK=false</code> for backend sign-in, or sign in to the OCR service below.</p></div>}
 {!status?.available&&<LocalLogin onSuccess={check}/>}<p>Use footage you own or have rights to process. Uploads stay on this computer and are purged after processing. Enter expected plates before running to get a blind accuracy measurement.</p>
 <div className="upload-zone" role="button" tabIndex={0} aria-label="Choose images or videos" onClick={()=>input.current?.click()} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.current?.click();}}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&!jobId)add(e.dataTransfer.files);}}>Drop images or videos, or choose files<input ref={input} type="file" multiple accept="image/png,image/jpeg,image/webp,video/mp4,video/webm,video/quicktime" disabled={busy||!!jobId} onChange={e=>{if(e.target.files)add(e.target.files);e.target.value='';}}/></div>
 <div className="upload-cards">{uploads.map(u=><UploadCard key={u.url} upload={u} expected={labels[u.file.name]||''} disabled={busy||!!job} onExpected={value=>setLabels({...labels,[u.file.name]:value})}/>)}</div>
 <label>Import labels CSV (filename,plate)<input type="file" accept=".csv,text/csv" disabled={busy||!!job} onChange={async e=>{try{const f=e.target.files?.[0];if(f)setLabels({...labels,...parseLabelsCSV(await f.text())});}catch(err){setError((err as Error).message);}}}/></label>
 <div className="filter-bar"><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="auto">Auto</option><option value="crop">Plate crop</option><option value="scene">Scene</option></select></label><label>Frame stride<input type="number" min={1} max={300} value={stride} onChange={e=>setStride(+e.target.value)}/></label><label>Max seconds<input type="number" min={1} max={60} value={seconds} onChange={e=>setSeconds(+e.target.value)}/></label><label>Purpose (required)<input minLength={5} maxLength={300} value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><label>Case reference<input maxLength={80} value={reference} onChange={e=>setReference(e.target.value)}/></label></div>
 <div className="flex gap-2"><button className="primary" disabled={busy||!!jobId||!status?.available||!authorised||!uploads.length||purpose.trim().length<5} onClick={()=>void run()}>Run OCR pipeline</button>{busy&&<button onClick={()=>void purge(false)}>Cancel</button>}<button onClick={()=>void purge(true)}>Clear and purge</button></div>
 {job&&<><div aria-live="polite"><strong>{job.state} · {job.stage}</strong><progress max={100} value={job.progress}/>{job.progress.toFixed(0)}%{job.error&&<p role="alert">{job.error}</p>}</div>{job.files.map((f:FileResult)=><p key={f.file}>{f.file}: {f.status}{f.error&&` · ${f.error}`}</p>)}{job.files.length>0&&<><ProvenanceChip source="live"/><div className="real-metric-grid"><div>Files processed<strong>{job.files.length}</strong></div><div>Accepted plates<strong>{plates.filter(p=>p.status==='read').length}</strong></div><div>Reads / abstains<strong>{plates.filter(p=>p.status==='read').length} / {plates.filter(p=>p.status==='abstain').length}</strong></div><div>Mean time / file<strong>{(job.files.reduce((s,f)=>s+(f.duration_ms||0),0)/job.files.length).toFixed(0)} ms</strong></div></div><p>{job.engine} {job.engine_version} · {job.device} · total {job.duration_ms?.toFixed(0)||'running'} ms · {job.purged?'Uploads purged':'Temporary uploads in use'}</p><ResultTable job={job} uploads={uploads} labels={labels} onLabel={(k,v)=>setLabels({...labels,[k]:v})}/><button disabled={job.state!=='done'} onClick={()=>void ocrRequest<OCRJob>(`jobs/${jobId}/labels`,{expected:labels}).then(setJob).catch(e=>setError(e.message))}>Save labels and recompute (not blind)</button><AccuracyPanel metrics={job.metrics}/><div className="flex gap-2"><button onClick={()=>save('ocr-results.json',JSON.stringify(exportJob(job,authorised),null,2),'application/json')}>Export JSON</button><button onClick={()=>save('ocr-results.csv',jobCSV(job,authorised),'text/csv;charset=utf-8')}>Export CSV</button></div></>}</>}
 </div></Panel>;
}

// A real backend session is separate from the seeded access profile; never send profile tokens as proof of identity.
import { loginOCRService } from './localSession';
function LocalLogin({onSuccess}:{onSuccess:()=>void}){const [user,setUser]=useState('officer'),[password,setPassword]=useState(''),[error,setError]=useState('');return <details><summary>Sign in to local OCR service</summary><form className="filter-bar" onSubmit={async e=>{e.preventDefault();try{await loginOCRService(user,password);setPassword('');setError('');onSuccess();}catch(err){setError((err as Error).message);}}}><label>User ID<input value={user} autoComplete="username" onChange={e=>setUser(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button>Sign in to OCR</button>{error&&<p role="alert">{error}</p>}</form></details>;}
