import { RoadLayer,useRoads } from '../real/RoadLayer';
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { LocateFixed, Minus, Plus } from 'lucide-react';
import type { Camera, Corridor, Density, Road, Trajectory } from '../types';
import boundary from '../demo/delhi-boundary.json';
import { REGIONS } from '../constants/city';
import { cameraById } from '../demo/model';

interface Props {focusCamera?:string;statusColors?:boolean;cameras:Camera[];roads:Road[];corridors?:Corridor[];density?:Density[];trajectory?:Trajectory|null;compare?:Trajectory|null;progress?:number;onCamera?:(camera:Camera)=>void;large?:boolean;region?:string;onRegion?:(region:string)=>void;heat?:boolean;flows?:{from:string;to:string;count:number}[]}
const EMPTY:never[]=[];
export const project=(lon:number,lat:number):[number,number]=>[(lon-76.83)*1550,(28.90-lat)*1770];
const shape=boundary.features[0].geometry.coordinates as number[][][];
const boundaryPath=shape.map(ring=>ring.map(([lon,lat],i)=>`${i?'L':'M'}${project(lon,lat).map(v=>v.toFixed(1)).join(',')}`).join(' ')+'Z').join(' ');
const river=[[77.22,28.86],[77.215,28.79],[77.23,28.74],[77.232,28.69],[77.255,28.65],[77.253,28.61],[77.285,28.56],[77.308,28.51],[77.325,28.44]].map(([lon,lat])=>project(lon,lat).join(',')).join(' ');
export default function NetworkMap({cameras,roads,corridors=EMPTY,density=EMPTY,trajectory,compare,progress=1,onCamera,focusCamera,statusColors=false,large=false,region:controlled,onRegion,heat=false,flows=EMPTY}:Props){
 const realRoads=useRoads(),[realMode,setRealMode]=useState(true);
 const [localRegion,setLocalRegion]=useState('All Delhi'),[showHeat,setShowHeat]=useState(heat),[selected,setSelected]=useState<Camera|null>(null),[zoom,setZoom]=useState(1),[pan,setPan]=useState<[number,number]>([0,0]);
 const drag=useRef<{x:number;y:number;pan:[number,number]}|null>(null),uid=useId().replace(/:/g,''),region=controlled??localRegion;
 const scoped=useMemo(()=>cameras.filter(c=>region==='All Delhi'||cameraById.get(c.id)?.region===region),[cameras,region]);
 const view=useMemo(()=>{if(region==='All Delhi')return [0,0,840,900];const points=scoped.map(c=>project(c.lon,c.lat));if(!points.length)return [0,0,840,900];const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),w=Math.max(170,Math.max(...xs)-Math.min(...xs)+110),h=Math.max(170,Math.max(...ys)-Math.min(...ys)+100);return [Math.min(...xs)-55,Math.min(...ys)-50,w,h];},[region,scoped]);
 const vb=[view[0]+view[2]*(1-1/zoom)/2+pan[0],view[1]+view[3]*(1-1/zoom)/2+pan[1],view[2]/zoom,view[3]/zoom].join(' ');
 const mapped=cameras.map(c=>realMode&&realRoads?.routes.real_position[c.id]?{...c,...realRoads.routes.real_position[c.id]}:c);
 const lookup=new Map(mapped.map(c=>[c.id,c])),max=Math.max(300,...density.map(d=>d.count));
 const targetCamera=lookup.get(focusCamera||'');
 const manualRegionFocus=useRef<string|undefined>(undefined);
 useEffect(()=>{if(!focusCamera||!targetCamera||manualRegionFocus.current===focusCamera)return;const [x,y]=project(targetCamera.lon,targetCamera.lat),targetZoom=Math.min(5,view[2]/200),targetPan:[number,number]=[x-view[0]-view[2]/2,y-view[1]-view[3]/2];setSelected(targetCamera);if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches){setZoom(targetZoom);setPan(targetPan);return;}let raf=0;const start=performance.now(),fromZoom=zoom,fromPan=pan;const frame=(now:number)=>{const t=Math.min(1,(now-start)/450),ease=1-(1-t)**3;setZoom(fromZoom+(targetZoom-fromZoom)*ease);setPan([fromPan[0]+(targetPan[0]-fromPan[0])*ease,fromPan[1]+(targetPan[1]-fromPan[1])*ease]);if(t<1)raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);return()=>cancelAnimationFrame(raf);},[focusCamera,targetCamera?.lat,targetCamera?.lon,realMode,region]);
 const realPoints=(ids:string[])=>ids.flatMap((id,i)=>{const c=lookup.get(id);if(!c)return [];if(i&&realMode){const r=realRoads?.routes.links[ids[i-1]+'-'+id];if(r)return r.coordinates.map(([lon,lat])=>project(lon,lat));}return [project(c.lon,c.lat)];});
 const pathFor=(t:Trajectory)=>t.hops.flatMap((h,i)=>{const ids=i?[...h.inferred_cameras,h.camera_id]:[h.camera_id];return ids.map(id=>lookup.get(id)).filter((c):c is Camera=>!!c).map(c=>project(c.lon,c.lat).join(','));}).join(' ');
 const changeRegion=(value:string)=>{manualRegionFocus.current=focusCamera;setZoom(1);setPan([0,0]);setSelected(null);if(onRegion)onRegion(value);else setLocalRegion(value);};
 const activeIndex=trajectory?Math.min(trajectory.hops.length-1,Math.floor(progress*Math.max(1,trajectory.hops.length-1))):0;
 return <div className={`network-map delhi-map ${large?'large':''}`}>
  {focusCamera&&!targetCamera&&<p role="status">Unknown camera ID. Showing the whole map.</p>}<svg className="delhi-svg" viewBox={vb} aria-label={`Delhi map, ${region}, ${scoped.length} modelled cameras`} role="img" onPointerDown={e=>{if((e.target as Element).closest('[data-camera]'))return;drag.current={x:e.clientX,y:e.clientY,pan};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current){const scale=view[2]/zoom/e.currentTarget.clientWidth;setPan([drag.current.pan[0]-(e.clientX-drag.current.x)*scale,drag.current.pan[1]-(e.clientY-drag.current.y)*scale]);}}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
   <defs><radialGradient id={`heat-${uid}`}><stop offset="0" stopColor="var(--heat-hot)" stopOpacity=".8"/><stop offset=".3" stopColor="var(--heat-mid)" stopOpacity=".6"/><stop offset=".65" stopColor="var(--heat-low)" stopOpacity=".3"/><stop offset="1" stopColor="var(--heat-low)" stopOpacity="0"/></radialGradient><pattern id={`grid-${uid}`} width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="var(--map-grid)" strokeWidth=".65"/></pattern><marker id={`arrow-${uid}`} viewBox="0 0 10 10" refX="7" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="var(--route)"/></marker></defs>
   <rect x="-5000" y="-5000" width="10000" height="10000" fill="var(--map-bg)"/><rect x="-5000" y="-5000" width="10000" height="10000" fill={`url(#grid-${uid})`}/>
   <path d={boundaryPath} fill="var(--map-land)" stroke="var(--map-boundary)" strokeWidth="2" fillRule="evenodd"/>
   <polyline points={river} fill="none" stroke="var(--map-river)" strokeWidth="12" strokeLinejoin="round"/>
   <text x="698" y="540" className="river-label" transform="rotate(65 698 540)">YAMUNA RIVER</text>
   {realMode&&realRoads&&<RoadLayer data={realRoads} project={project}/>}
   {roads.map(r=>{const a=lookup.get(r.from),b=lookup.get(r.to);if(!a||!b)return null;const colour=corridors.find(c=>c.from===r.from&&c.to===r.to)?.level||'unknown',visible=region==='All Delhi'||scoped.some(c=>c.id===a.id||c.id===b.id);const realLink=realMode?realRoads?.routes.links[r.from+'-'+r.to]:null;if(realLink)return <polyline key={r.from+r.to} points={realLink.coordinates.map(([lon,lat])=>project(lon,lat).join(',')).join(' ')} fill="none" vectorEffect="non-scaling-stroke" className={`map-road ${colour}`} opacity={visible?1:.15}><title>{a.name} → {b.name}: road {realLink.road_distance_km.toFixed(2)} km; straight {realLink.straight_distance_km.toFixed(2)} km</title></polyline>;return <g key={r.from+r.to} opacity={visible?1:.15}><line x1={project(a.lon,a.lat)[0]} y1={project(a.lon,a.lat)[1]} x2={project(b.lon,b.lat)[0]} y2={project(b.lon,b.lat)[1]} className="map-road-casing"/><line x1={project(a.lon,a.lat)[0]} y1={project(a.lon,a.lat)[1]} x2={project(b.lon,b.lat)[0]} y2={project(b.lon,b.lat)[1]} className={`map-road ${colour}`}><title>{a.name} → {b.name} · illustrative road link</title></line></g>;})}
   {showHeat&&scoped.map(c=>{const p=project(c.lon,c.lat),count=density.find(d=>d.camera_id===c.id)?.count||0;return <circle key={c.id} cx={p[0]} cy={p[1]} r={18+count/max*65} fill={`url(#heat-${uid})`} opacity={.3+count/max*.65}><title>{c.name}: {count} modelled passes</title></circle>;})}
   {flows.map((f,i)=>{const a=lookup.get(f.from),b=lookup.get(f.to);if(!a||!b||a===b)return null;const [x,y]=project(a.lon,a.lat),[xx,yy]=project(b.lon,b.lat);return <path key={i} d={`M${x},${y}Q${(x+xx)/2-45},${(y+yy)/2-65} ${xx},${yy}`} fill="none" stroke="var(--route-b)" strokeWidth={Math.min(7,1+f.count/2)} opacity=".65"><title>{a.name} → {b.name}: {f.count} trips</title></path>;})}
   {compare&&<polyline points={pathFor(compare)} fill="none" stroke="var(--route-b)" strokeWidth="5" strokeDasharray="4 3"/>}
   {trajectory?.hops.map((h,i)=>{if(i===0||i>activeIndex+1)return null;const prev=trajectory.hops[i-1],pts=realPoints([prev.camera_id,...h.inferred_cameras,h.camera_id]);const fraction=Math.max(0,Math.min(1,progress*(trajectory.hops.length-1)-(i-1))),step=Math.min(pts.length-2,Math.floor(fraction*(pts.length-1))),ratio=fraction===1?1:fraction*(pts.length-1)-step;if(!fraction||pts.length<2)return null;const a=pts[step],b=pts[step+1],end:[number,number]=[a[0]+(b[0]-a[0])*ratio,a[1]+(b[1]-a[1])*ratio];return <g key={h.detection_id}><polyline points={[...pts.slice(0,step+1),end].map(p=>p.join(',')).join(' ')} className="journey-line" strokeDasharray={h.inferred_cameras.length?'8 5':undefined} markerEnd={`url(#arrow-${uid})`}/>{(fraction<1||i===trajectory.hops.length-1)&&<g className="moving-vehicle"><circle cx={end[0]} cy={end[1]} r="14"/><text x={end[0]} y={end[1]+4} textAnchor="middle">▶</text></g>}</g>;})}
   {mapped.map(c=>{const [x,y]=project(c.lon,c.lat),visible=region==='All Delhi'||scoped.some(s=>s.id===c.id);const stop=trajectory?.hops.findIndex((h,i)=>h.camera_id===c.id&&i<=activeIndex);return <g key={c.id} data-camera={c.id} role="button" tabIndex={visible?0:-1} aria-label={`${c.name}, ${c.id}`} opacity={visible?1:.15} onClick={()=>{setSelected(c);onCamera?.(c);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(c);onCamera?.(c);}}} className={`svg-camera ${selected?.id===c.id?'camera-selected':''} ${focusCamera===c.id?'camera-focused':''}`}><circle cx={x} cy={y} r={stop!==undefined&&stop>=0?12:5} style={statusColors?{fill:({Online:'#168f81',Degraded:'#d5983e',Offline:'#cf6164'} as Record<string,string>)[(c as Camera & {status?:string}).status||'']||'#829ab7'}:undefined} className={stop!==undefined&&stop>=0?'route-stop':'camera-dot'}/>{stop!==undefined&&stop>=0&&<text x={x} y={y+4} textAnchor="middle" className="stop-number">{stop+1}</text>}{(region!=='All Delhi'||selected?.id===c.id||['C01','C10','C13','C22','C23','C30','C34','C37'].includes(c.id))&&<text x={x+10} y={y-9} className="map-city-label" style={{fontSize:region==='All Delhi'?14:4.5}}>{c.name}</text>}<title>{c.id} · {c.name} · modelled</title></g>;})}
   {region==='All Delhi'&&<><text x="95" y="230" className="map-region-name">NORTH WEST</text><text x="145" y="490" className="map-region-name">WEST DELHI</text><text x="510" y="185" className="map-region-name">NORTH DELHI</text><text x="370" y="690" className="map-region-name">SOUTH DELHI</text></>}
  </svg>
  <div className="map-tools">{realRoads&&<button aria-pressed={realMode} onClick={()=>setRealMode(!realMode)}>{realMode?'Real roads':'Schematic roads'}</button>}<label className="map-region-control"><span>Region</span><select aria-label="Map region" value={region} onChange={e=>changeRegion(e.target.value)}><option>All Delhi</option>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></label><button className={showHeat?'selected':''} aria-pressed={showHeat} onClick={()=>setShowHeat(!showHeat)}>Heatmap</button></div>
  <div className="map-zoom"><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(5,z*1.4))}><Plus size={15}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(1,z/1.4))}><Minus size={15}/></button><button aria-label="Reset map view" onClick={()=>{setZoom(1);setPan([0,0]);}}><LocateFixed size={15}/></button></div>
  <div className="map-information"><span className="eyebrow">{selected?selected.id:'NCT OF DELHI'}</span><strong>{selected?.name||region}</strong><small>{selected?`${density.find(d=>d.camera_id===selected.id)?.count||0} modelled sightings`:`${scoped.length} modelled cameras · drag to pan`}</small></div><div className="map-north">N<span>↑</span></div>
  <a className="map-attribution" href="https://github.com/datameet/Municipal_Spatial_Data/tree/master/Delhi" target="_blank" rel="noreferrer">{realMode&&realRoads?'Road data © OpenStreetMap contributors (ODbL) · Boundary: DataMeet · cameras illustrative':'Boundary: DataMeet / CC BY-SA 2.5 IN · roads & regions illustrative'}</a>
 </div>;
}
