import { ProvenanceChip } from '../lib/provenance';
import { useState } from 'react';
import { Badge, Panel } from './UI';
import { PlateCrop } from './SimulatedFeed';
import { record } from '../demo/api';
import { ocrConditions, ocrReview } from '../demo/model';
export default function OCRDemo(){const [queue,setQueue]=useState(()=>structuredClone(ocrReview)),[message,setMessage]=useState('');const accuracy=ocrConditions.reduce((s,c)=>s+c.correct,0)/ocrConditions.reduce((s,c)=>s+c.total,0)*100;
 function resolve(id:number,action:string){const row=queue.find(r=>r.id===id)!;setQueue(q=>q.filter(r=>r.id!==id));setMessage(`Read ${id}: ${action}. sample review recorded.`);record('ocr.review',{id,action,plate:row.plate});}
 return <><h2>Reference benchmark <ProvenanceChip source="modelled"/></h2><div className="journey-stats"><div><small>Reference plate accuracy</small><strong>{accuracy.toFixed(1)}%</strong><Badge tone="green">Modelled reference value</Badge></div><div><small>Character error rate</small><strong>2.4%</strong></div><div><small>modelled inference latency</small><strong>42 ms</strong></div><div><small>Human review queue</small><strong>{queue.length}</strong></div></div><div className="two-columns"><Panel source="modelled" title="Accuracy by condition" subtitle="Fixed sample benchmark, not a measurement of a deployed OCR model"><div className="padded">{ocrConditions.map(c=><div className="ocr-condition" key={c.name}><span>{c.name}</span><i><b style={{width:`${c.correct/c.total*100}%`}}/></i><strong>{(c.correct/c.total*100).toFixed(1)}%</strong></div>)}</div></Panel><Panel source="modelled" title="Human-review queue" subtitle="Confirm, correct or reject a modelled plate read"><div className="padded">{message&&<p className="muted" role="status">{message}</p>}{queue.map(row=><div className="ocr-review" key={row.id}><PlateCrop plate={row.crop}/><label>Reading · {row.confidence}% modelled confidence<input aria-label={`Correct reading ${row.id}`} value={row.plate} onChange={e=>setQueue(q=>q.map(r=>r.id===row.id?{...r,plate:e.target.value.toUpperCase()}:r))}/></label><div className="flex gap-2"><button onClick={()=>resolve(row.id,'Confirmed')}>Confirm</button><button className="primary" onClick={()=>resolve(row.id,'Corrected')} disabled={!row.plate.trim()}>Correct</button><button onClick={()=>resolve(row.id,'Rejected')}>Reject</button></div></div>)}{!queue.length&&<Badge tone="green">Review queue cleared for this visit</Badge>}</div></Panel></div></>;
}
