import { ProvenanceChip } from '../lib/provenance';
import { useEffect, useId, useState } from 'react';
import { useReducedMotion } from 'framer-motion';
import { useSession } from '../session';
import { vehicles, cameraById } from '../demo/model';

export function PlateCrop({plate}:{plate:string}){return <div className="plate-crop" aria-label={`modelled plate crop ${plate}`}><small>IND</small><strong>{plate}</strong><span>modelled CROP</span></div>;}
export default function SimulatedFeed({camera='C01',plate='DL01AB1234',compact=false,paused=false}:{camera?:string;plate?:string;compact?:boolean;paused?:boolean}){
 const {session}=useSession();const shownPlate=session?.user.role==='viewer'?plate.replace(/^([A-Z]{2})([0-9]{2})[A-Z]+([0-9]{4})$/,'$1-$2-**-$3'):plate;const id=useId().replace(/:/g,''),reduced=useReducedMotion(),[hidden,setHidden]=useState(document.hidden);const vehicle=vehicles.find(v=>v.plate===plate)||vehicles[0],name=cameraById.get(camera)?.name||camera;
 useEffect(()=>{const listener=()=>setHidden(document.hidden);document.addEventListener('visibilitychange',listener);return()=>document.removeEventListener('visibilitychange',listener);},[]);
 return <div className={`cctv-feed ${compact?'compact':''} ${paused||hidden||reduced?'feed-paused':''}`}><div className="feed-heading"><span><i/> {camera} / {name}</span><b>{<ProvenanceChip source="modelled"/>}</b></div><svg viewBox="0 0 640 360" role="img" aria-label={`modelled CCTV at ${name}, ${shownPlate}. Generated camera view.`}>
  <defs><pattern id={`pavement-${id}`} width="36" height="36" patternUnits="userSpaceOnUse"><rect width="36" height="36" className="feed-pavement"/><path d="M36 0H0V36" className="feed-paver"/></pattern><linearGradient id={`road-${id}`} x1="0" y1="0" x2="1" y2="1"><stop stopColor="var(--feed-road-a)"/><stop offset="1" stopColor="var(--feed-road-b)"/></linearGradient></defs>
  <rect width="640" height="360" fill={`url(#pavement-${id})`}/><path d="M-70 320L360 -60H730L240 420Z" fill={`url(#road-${id})`}/><path d="M-50 341L412 -55M207 420L690 -40" className="feed-curb"/><path d="M35 361L485 -48M135 400L583 -40" className="feed-lane"/><path d="M83 390L531 -35" className="feed-divider"/>
  {[25,90,580,620].map((x,i)=><g key={x} transform={`translate(${x} ${i<2?55:290})`}><circle r="28" className="feed-tree-shadow"/><circle cx="-4" cy="-5" r="25" className="feed-tree"/><circle cx="-9" cy="-11" r="17" className="feed-tree-light"/></g>)}
  {[0,1,2,3,4].map((n)=><g key={n} className={`feed-car-path feed-car-${n}`}><g transform="rotate(-42)"><rect x="-24" y="-45" width="52" height="94" rx="12" className="car-shadow"/><rect x="-24" y="-36" width="6" height="15" className="car-tyre"/><rect x="20" y="-36" width="6" height="15" className="car-tyre"/><rect x="-24" y="22" width="6" height="15" className="car-tyre"/><rect x="20" y="22" width="6" height="15" className="car-tyre"/><rect x="-20" y="-44" width="42" height="88" rx="10" className={`car-body colour-${n===0?vehicle.colour.toLowerCase():['silver','blue','white','red'][n-1]}`}/><path d="M-15 -23H17L14 -8H-12Z M-12 14H14L17 29H-15Z" className="car-glass"/><rect x="-13" y="-4" width="28" height="15" rx="3" className="car-roof"/><path d="M-16 -39H-8M10 -39H18" className="car-light"/><rect x="-10" y="34" width="23" height="6" rx="1" className="car-plate"/></g>{n===0&&<g className="feed-tracking"><rect x="-59" y="-60" width="118" height="120" rx="3"/><rect x="-60" y="-86" width="154" height="22" className="tracking-label-bg"/><text x="-53" y="-71">{shownPlate} · Modelled {Math.round(vehicle.confidence*100)}%</text></g>}</g>)}
  <rect x="8" y="319" width="295" height="28" className="feed-osd-bg"/><text x="18" y="337" className="feed-osd">sample 2026-09-30 • VEHICLE TRACK REPLAY</text>
 </svg><div className="feed-caption"><span>{shownPlate} · {vehicle.colour} {vehicle.make} {vehicle.model}</span><span>Scripted overlay</span></div></div>;
}
