import { useMemo } from 'react';
import { Line,LineChart,Bar,BarChart,XAxis,YAxis,Tooltip,ResponsiveContainer } from 'recharts';
import { Panel } from '../components/UI';
import { reads,cameraById,routeBetween,corridorsAt,type DemoRead } from '../demo/model';
import { percentile,bufferIndex } from './calculations';
const Chart=({data,field}:{data:Record<string,string|number>[];field:string})=><div style={{height:230}}><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey={field} fill="#398d79" isAnimationActive={false}/></BarChart></ResponsiveContainer></div>;
export default function DeepDetails({rows,region}:{rows:DemoRead[];region:string}){
 const stats=useMemo(()=>{const ids=new Set(rows.map(r=>r.id)),groups=new Map<string,DemoRead[]>();for(const r of reads){const key=`${r.identity_id}-${new Date(Date.parse(r.timestamp)+19800000).toISOString().slice(0,10)}`;groups.set(key,[...(groups.get(key)||[]),r]);}const trips=[...groups.values()].filter(g=>g.some(r=>ids.has(r.id))).map(g=>{let km=0;const segments:number[]=[];for(let i=1;i<g.length;i++){km+=routeBetween(g[i-1].camera_id,g[i].camera_id).distance;segments.push((Date.parse(g[i].timestamp)-Date.parse(g[i-1].timestamp))/60000);}return {km,minutes:(Date.parse(g.at(-1)!.timestamp)-Date.parse(g[0].timestamp))/60000,segments};});const hours=Array.from({length:24},(_,hour)=>{const rs=rows.filter(r=>new Date(Date.parse(r.timestamp)+19800000).getUTCHours()===hour),cs=corridorsAt(hour).filter(c=>region==='All Delhi'||cameraById.get(c.from)?.region===region||cameraById.get(c.to)?.region===region);return {hour,confidence:rs.length?rs.reduce((n,r)=>n+(r.confidence||0),0)/rs.length*100:0,congestion:cs.reduce((n,c)=>n+(c.congestion_index||0),0)/Math.max(1,cs.length),p10:percentile(rs.map(r=>r.speed),.1),p50:percentile(rs.map(r=>r.speed),.5),p90:percentile(rs.map(r=>r.speed),.9)};});return {trips,hours};},[rows,region]);
 const bins=(values:number[],size:number,count=8)=>Array.from({length:count},(_,i)=>({name:i===count-1?`${i*size}+`:`${i*size}–${(i+1)*size}`,count:values.filter(v=>Math.min(count-1,Math.floor(v/size))===i).length})),durations=stats.trips.map(t=>t.minutes),p95=percentile(durations,.95),med=percentile(durations,.5);
 return <><div className="two-columns mt-panel"><Panel title="Daily journey lengths" subtitle="Full vehicle-day paths intersecting the filter · inferred schematic distance"><Chart data={bins(stats.trips.map(t=>t.km),20)} field="count"/></Panel><Panel title="Daily journey duration" subtitle="Minutes from first to last read, including stops"><Chart data={bins(durations,90)} field="count"/></Panel></div><div className="two-columns mt-panel"><Panel title="Journey reliability"><div className="padded"><div className="stat-pair"><span>Vehicle-days</span><strong>{stats.trips.length}</strong></div><div className="stat-pair"><span>P50 / P95 duration</span><strong>{med?.toFixed(1)??'—'} / {p95?.toFixed(1)??'—'} min</strong></div><div className="stat-pair"><span>Buffer index (P95 − mean) / mean</span><strong>{bufferIndex(durations)?.toFixed(2)??'—'}</strong></div><p className="muted">Describes complete seeded daily journeys, not comparable commutes or measured real-road travel times.</p></div></Panel><Panel title="Dwell distribution" subtitle="Minutes at stops with positive seeded dwell"><Chart data={bins(rows.filter(r=>r.dwell>0).map(r=>r.dwell/60),30,6)} field="count"/></Panel></div><div className="two-columns mt-panel"><Panel title="Hourly congestion index" subtitle="Separate seeded corridor traffic model · lower is freer"><div style={{height:240}}><ResponsiveContainer width="100%" height="100%"><LineChart data={stats.hours}><XAxis dataKey="hour"/><YAxis/><Tooltip/><Line dataKey="congestion" stroke="#d29644" isAnimationActive={false}/></LineChart></ResponsiveContainer></div></Panel><Panel title="Hourly speed quantiles" subtitle="modelled plate observations · km/h"><div style={{height:240}}><ResponsiveContainer width="100%" height="100%"><LineChart data={stats.hours}><XAxis dataKey="hour"/><YAxis/><Tooltip/>{['p10','p50','p90'].map((k,i)=><Line key={k} dataKey={k} stroke={['#94bfb8','#248873','#7969a5'][i]} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div></Panel></div></>;
}
