import { useEffect,useRef,useState } from 'react';
import { Link } from '../router';
import { Modal,Panel } from '../components/UI';
import { cameraById } from '../demo/model';
import { ProvenanceChip } from '../lib/provenance';
import { useSession } from '../session';
import { liveFeeds,type LiveFeed } from './liveFeeds.config';
import { useMeasureVideo,useStreamMeasurements } from './streamMeasurements';
import { useDetectionOverlay,type OverlayAnalysis } from './DetectionOverlay';
export const locateCamera=(id:string)=>`/map?camera=${encodeURIComponent(id)}&focus=1`;
export function FeedTile({feed,paused=false,expanded=false,onExpand}:{feed:LiveFeed;paused?:boolean;expanded?:boolean;onExpand?:()=>void}){const video=useRef<HTMLVideoElement>(null),canvas=useRef<HTMLCanvasElement>(null),[error,setError]=useState(false),[blocked,setBlocked]=useState(false),[localPause,setLocalPause]=useState(false),[analysis,setAnalysis]=useState<OverlayAnalysis|null>(null),[overlay,setOverlay]=useState(true),measurements=useStreamMeasurements(),{session}=useSession();const camera=cameraById.get(feed.camera_id),viewer=session?.user.role==='viewer';
 useMeasureVideo(feed.camera_id,video,analysis);useDetectionOverlay(video,canvas,analysis,overlay,viewer);
 useEffect(()=>{const ctrl=new AbortController();fetch(`/real/analysis/${feed.id}.json`,{signal:ctrl.signal}).then(async r=>{if(r.ok&&r.headers.get('content-type')?.includes('json')){const value=await r.json();if(value.fps>0&&Array.isArray(value.frames))setAnalysis(value);}}).catch(()=>{});return()=>ctrl.abort();},[feed.id]);
 useEffect(()=>{const v=video.current;if(!v)return;let visible=false;const sync=()=>{if(visible&&!paused&&!localPause&&!document.hidden&&!error)void v.play().then(()=>setBlocked(false)).catch(()=>setBlocked(true));else v.pause();};const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;sync();},{threshold:.2});observer.observe(v);document.addEventListener('visibilitychange',sync);sync();return()=>{observer.disconnect();document.removeEventListener('visibilitychange',sync);v.pause();};},[paused,localPause,error]);
 useEffect(()=>{const v=video.current;if(v)v.src=feed.file;return()=>{if(v){v.pause();v.removeAttribute('src');v.load();}};},[feed.file]);
 const m=measurements[feed.camera_id];return <Panel className={`live-feed ${expanded?'expanded':''}`}><div className="padded"><div className="spread"><strong>{feed.camera_id} · {camera?.name||feed.title}</strong><span>{error?'Unavailable':paused||localPause?'Paused':m?.playing?m.stalled?'Stalled':'Playing':'Recorded'}</span></div><small>{camera?.region}</small><div className="flex gap-2"><ProvenanceChip source="recorded"/><ProvenanceChip source="staged"/></div></div><div className="real-video-stage"><video ref={video} src={feed.file} muted loop playsInline preload="metadata" controls={expanded} aria-label={`Recorded feed ${feed.camera_id}`} onError={()=>setError(true)}/><canvas ref={canvas} aria-hidden="true"/>{blocked&&<button className="tap-to-play" onClick={()=>{setLocalPause(false);void video.current?.play().then(()=>setBlocked(false)).catch(()=>setBlocked(true));}}>Tap to play</button>}</div>{error?<p role="alert">Video unavailable · {feed.file.split('/').pop()}</p>:null}<div className="feed-controls"><button onClick={()=>setLocalPause(!localPause)}>{localPause?'Play':'Pause'}</button>{onExpand&&<button onClick={onExpand}>Expand {feed.camera_id}</button>}<Link className="button" to={locateCamera(feed.camera_id)}>Locate</Link>{analysis?<label><input type="checkbox" checked={overlay} onChange={e=>setOverlay(e.target.checked)}/>Detections</label>:<small>No detections loaded</small>}</div>{expanded&&<p className="padded mono">{camera?.lat.toFixed(6)}, {camera?.lon.toFixed(6)} · {feed.duration.toFixed(2)}s · {feed.width}×{feed.height} · {feed.fps.toFixed(2)} fps</p>}</Panel>;}
export default function LiveFeeds({feeds=liveFeeds}:{feeds?:LiveFeed[]}){const [paused,setPaused]=useState(false),[layout,setLayout]=useState('grid'),[focus,setFocus]=useState(feeds[0]?.id),[expanded,setExpanded]=useState<LiveFeed|null>(null);const ordered=[...feeds].sort((a,b)=>layout==='focus'?Number(b.id===focus)-Number(a.id===focus):0);return <section aria-label="Recorded camera feeds"><div className="filter-bar standalone"><h2>Camera feeds</h2><button aria-pressed={layout==='grid'} onClick={()=>setLayout('grid')}>Grid</button><button aria-pressed={layout==='focus'} onClick={()=>setLayout('focus')}>Focus</button>{layout==='focus'&&<label>Focus camera<select value={focus} onChange={e=>setFocus(e.target.value)}>{feeds.map(f=><option key={f.id} value={f.id}>{f.camera_id}</option>)}</select></label>}<button onClick={()=>setPaused(!paused)}>{paused?'Play all':'Pause all'}</button></div><div className={`recorded-grid ${layout}`}>{ordered.map(feed=><FeedTile key={feed.id} feed={feed} paused={paused||!!expanded} onExpand={()=>setExpanded(feed)}/>)}</div>{!feeds.length&&<p>No recorded feeds configured.</p>}{expanded&&<Modal title={`${expanded.camera_id} · Recorded feed`} onClose={()=>setExpanded(null)}><FeedTile feed={expanded} expanded/><button onClick={()=>setExpanded(null)}>Close viewer</button></Modal>}</section>;}
