import { ProvenanceChip } from '../lib/provenance';
import MeasuredErrors from './MeasuredErrors';
import { Panel,Badge } from '../components/UI';
import { useRealFootage } from './context';
import SourceBadge from './SourceBadge';
import type { Accuracy } from './types';
import { ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip } from 'recharts';
const figure=(a:Accuracy|null|undefined)=>a?`${(a.value*100).toFixed(1)}% · N=${a.n} · 95% CI ${(a.ci95[0]*100).toFixed(1)}–${(a.ci95[1]*100).toFixed(1)}%`:'Not measured';
export default function MeasuredOCR(){const {bundle}=useRealFootage(),m=bundle?.metrics;return <><Panel title="Measured on real footage" subtitle="Exact-match plate accuracy after multi-frame voting" className="mt-panel"><div className="padded">{m?.split==='test'?<ProvenanceChip source="frozen"/>:<SourceBadge/>}<p className="real-notice">{m?.status||'Not measured: no ground-truth labels'}. {m?.plate_accuracy_readable?'Abstentions count as incorrect. Eligibility is fixed before evaluation.':'The 90% target has not been demonstrated. No plate strings have been invented.'}</p><div className="real-metric-grid"><div><small>Readable-plate accuracy</small><p>{figure(m?.plate_accuracy_readable)}</p></div><div><small>All-tracks accuracy</small><p>{figure(m?.plate_accuracy_all)}</p></div><div><small>CER</small><strong>{m?.cer==null?'—':`${(m.cer*100).toFixed(1)}%`}</strong></div><div><small>Coverage</small><strong>{m?.coverage==null?'—':`${(m.coverage*100).toFixed(1)}%`}</strong></div></div>{m&&<><p>{m.n_tracks} {m.split?'labelled tracks':'model tracks'} · eligible labelled tracks: {m.n_eligible??'not measured'} · split: {m.split||'not evaluated'}</p>{m.n_eligible!=null&&m.n_eligible<400&&<Badge tone="amber">Small sample: the interval is too wide for a reliable 90% claim</Badge>}<p>Selective accuracy: {figure(m.selective_accuracy)}</p>{m.coverage_curve.length>0&&<div style={{height:220}}><ResponsiveContainer width="100%" height="100%"><LineChart data={m.coverage_curve}><XAxis dataKey="coverage"/><YAxis domain={[0,1]}/><Tooltip/><Line dataKey="accuracy" stroke="#168f81" isAnimationActive={false}/></LineChart></ResponsiveContainer></div>}{Object.entries(m.by_condition).map(([c,v])=><p key={c}>{c}: {figure(v)}</p>)}<details><summary>Models, versions and reproducibility</summary>{Object.entries(m.models).map(([k,v])=><p key={k} className="hash-text">{k}: {v}</p>)}<p className="hash-text">Config SHA-256: {m.config_hash}</p></details></>}</div></Panel><MeasuredErrors/></>;}
