import { useState } from 'react';
import { Link,useParams } from '../router';
import { useRealFootage } from './context';
import ClipEvidence from './ClipEvidence';
import SourceBadge from './SourceBadge';
import { Panel,Page,PageHeader,Empty } from '../components/UI';
import RealVideo from './RealVideo';
import { record } from '../demo/api';
export function RealMatches({query}:{query:string}){const {bundle}=useRealFootage(),q=query.toUpperCase().replace(/[^A-Z0-9]/g,''),matches=bundle?.trajectories.filter(t=>!q||t.plate.includes(q))||[];return <Panel title="Real-footage identity matches" className="mt-panel"><div className="padded">{matches.length?matches.map(t=><p key={t.plate}><SourceBadge reviewed={t.stops.some(s=>s.identity_source==='user_confirmed')}/><Link to={`/real-vehicles/${t.plate}`}>{t.plate} · {t.stops.length} real sightings →</Link></p>):<p>No recorded or reviewed plate matches this search.</p>}</div></Panel>;}
export default function RealProfile(){const {id}=useParams(),{bundle}=useRealFootage(),[reason,setReason]=useState(''),[accepted,setAccepted]=useState(false),[index,setIndex]=useState(0);const trajectory=bundle?.trajectories.find(t=>t.plate===id),stops=trajectory?.stops||[],stop=stops[index],registry=id?bundle?.registry[id]:null;
 if(!accepted)return <Page><Panel title="Authorised real-evidence access"><form className="padded form-stack" onSubmit={e=>{e.preventDefault();record('real.vehicle.profile',{plate:id,reason:reason.trim()||'Uploaded evidence review'});setAccepted(true);}}><label>Additional case reference (optional)<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary">Open real profile</button></form></Panel></Page>;
 return <Page><PageHeader title={id||'Real vehicle profile'} description="Recorded or user-confirmed identity · human verification required"/>{!trajectory?<Empty title="No real identity record" message="No accepted plate read exists for this registration."/>:<><Panel title="Real footage sightings"><div className="padded"><SourceBadge staged={stop?.staged} reviewed={stop?.identity_source==='user_confirmed'}/><div className="filter-bar">{stops.map((s,i)=><button key={`${s.clip_id}-${s.track_id}`} onClick={()=>setIndex(i)}>{s.camera_id} · {s.ts_ist} · {s.identity_source==='user_confirmed'?'User-confirmed':`${(s.confidence*100).toFixed(1)}%`}</button>)}</div>{stop&&(bundle?.manifest.clips.find(c=>c.id===stop.clip_id)?.evidence?<ClipEvidence clipId={stop.clip_id}/>:<RealVideo clipId={stop.clip_id} seek={stop.video_time_s} trackId={stop.track_id}/>)}</div></Panel><Panel title="Registry"><div className="padded">{registry?<><SourceBadge synthetic/><p>User-provided consented-vehicle entry. Not connected to a government registry.</p>{Object.entries(registry).map(([k,v])=><div className="stat-pair" key={k}><span>{k}</span><strong>{/owner|address|contact|engine|chassis/i.test(k)?'•••• (restricted)':v}</strong></div>)}</>:<p>No registry record (connector not configured)</p>}</div></Panel></>}</Page>;
}
