import { useEffect,useState } from 'react';
import { Panel,Modal,Badge } from '../components/UI';
import { useRealFootage } from './context';
import RealVideo from './RealVideo';
import ClipEvidence from './ClipEvidence';
import SourceBadge,{maskPlate} from './SourceBadge';
import { useSession } from '../session';
import { record } from '../demo/api';
import type { RealEvent } from './types';

export default function RealAlerts(){
 const {bundle,workflow,setWorkflow}=useRealFootage(),{session}=useSession(),[selected,setSelected]=useState<RealEvent|null>(null),[draft,setDraft]=useState({status:'Open',assignee:'',note:''}),[running,setRunning]=useState(false),[step,setStep]=useState(0);
 const events=[...(bundle?.events||[])].sort((a,b)=>Number(b.type==='clone_suspect')-Number(a.type==='clone_suspect')),state=selected?draft:null;
 useEffect(()=>{if(!running||!events.length)return;const timer=setInterval(()=>setStep(i=>{if(i>=events.length-1){setRunning(false);return i;}return i+1;}),3000);return()=>clearInterval(timer);},[running,events.length]);
 if(!events.length)return null;
 return <Panel title="Video evidence cases" subtitle={`${events.length} alerts · test watchlist matches and duplicate-plate review`} className="mt-panel" action={<button onClick={()=>{setStep(0);setRunning(!running);}}>{running?'Stop replay':'Replay case alerts'}</button>}><div className="padded video-case-cards">{(running?events.slice(0,step+1):events).map(e=><article className="video-case-card" key={e.id}><SourceBadge staged={e.staged} reviewed={e.identity_source==='user_confirmed'}/><h3>{e.type==='clone_suspect'?'Suspected cloned plate':'Test blacklist match'} · {maskPlate(e.plate==='AI07204'?'AI 0720-4':e.plate,session?.user.role==='viewer')}</h3><p>{e.type==='clone_suspect'?'Two vehicles · two recordings · compare the evidence':`${bundle?.manifest.clips.find(c=>c.id===e.clip_id)?.evidence?.vehicle_label||e.clip_id} · user-requested test watchlist`}</p><Badge>{workflow[e.id]?.status||'Open'}</Badge><button className="primary" onClick={()=>{setDraft(workflow[e.id]||{status:'Open',assignee:'',note:''});setSelected(e);}}>{e.type==='clone_suspect'?'Review both vehicles':'Review blacklist evidence'}</button></article>)}</div>{selected&&state&&<Modal title={selected.type==='clone_suspect'?`Cloned plate review · ${selected.plate==='AI07204'?'AI 0720-4':selected.plate}`:'Blacklist evidence review'} onClose={()=>setSelected(null)}><div className="spread"><Badge tone="amber">Human review required</Badge><button onClick={()=>setSelected(null)}>Close evidence</button></div><p className="real-notice">{selected.explanation}</p><div className="two-evidence-grid">{(selected.sightings||[selected]).map(s=>bundle?.manifest.clips.find(c=>c.id===s.clip_id)?.evidence?<ClipEvidence key={s.clip_id} clipId={s.clip_id}/>:<RealVideo key={s.clip_id} clipId={s.clip_id} seek={s.video_time_s} trackId={s.track_id}/>)}</div>{selected.distance_km!=null&&<p>{selected.distance_km.toFixed(2)} km · {selected.implied_kmh?.toFixed(1)} km/h implied by assigned times. Placements may be illustrative.</p>}<form className="form-stack" onSubmit={e=>{e.preventDefault();setWorkflow(w=>({...w,[selected.id]:state}));record('real.alert.workflow',{id:selected.id,...state});setSelected(null);}}><label>Status<select value={state.status} onChange={e=>setDraft({...state,status:e.target.value})}>{['Open','Acknowledged','Verified','Dispatched','Closed','False Positive'].map(s=><option key={s}>{s}</option>)}</select></label><label>Assignee<input value={state.assignee} onChange={e=>setDraft({...state,assignee:e.target.value})}/></label><label>Review note<textarea value={state.note} onChange={e=>setDraft({...state,note:e.target.value})}/></label><button className="primary">Save review</button></form></Modal>}</Panel>;
}
