import { useSession } from '../session';
import { useState } from 'react';
import { Panel,Empty,Badge } from '../components/UI';
import { useRealFootage } from './context';
import RealVideo from './RealVideo';
import SourceBadge,{maskPlate} from './SourceBadge';
export default function RealWorkspace(){const {session}=useSession(),{bundle,loading,error}=useRealFootage(),[chosen,setChosen]=useState(''),[seek,setSeek]=useState(0),[selected,setSelected]=useState<number>();const clip=bundle?.manifest.clips.find(c=>c.id===chosen)||bundle?.manifest.clips[0],tracks=clip?bundle?.tracks[clip.id]||[]:[],counts=clip?bundle?.counts[clip.id]:null;
 return <Panel title="Real footage · pipeline output" subtitle="Actual model detections from the bundled licensed recordings"><div className="padded">{!clip?<Empty title={loading?'Loading recordings…':error||'No real footage bundle loaded'} message="The existing demo remains available. Run python -m pipeline run-all to add local video results."/>:<><div className="filter-bar"><label>Recording<select aria-label="Real recording" value={clip.id} onChange={e=>{setChosen(e.target.value);setSeek(0);setSelected(undefined);}}>{bundle!.manifest.clips.map(c=><option key={c.id} value={c.id}>{c.id} · {c.duration_s.toFixed(1)}s</option>)}</select></label><SourceBadge/><Badge>{tracks.length} model tracks</Badge><Badge>{counts?.crossings.length||0} line crossings</Badge></div><div className="real-workspace-grid"><RealVideo clipId={clip.id} seek={seek} trackId={selected}/><div><h3>Recorded clip measurements</h3><p className="muted">Counts are from these clips, not city traffic. Class and colour are model estimates.</p>{Object.entries(counts?.track_classes||{}).map(([name,n])=><div className="stat-pair" key={name}><span>{name}</span><strong>{n}</strong></div>)}<div className="stat-pair"><span>Median visible dwell</span><strong>{counts?.dwell.median_s?.toFixed(1)??'—'}s</strong></div><p className="capability-note">No plate models configured for these samples. Plate reads abstain; number plates are never invented.</p><div className="real-track-list" aria-label="Detected vehicle tracks">{tracks.map(t=><button key={t.track_id} className={selected===t.track_id?'selected':''} onClick={()=>{setSelected(t.track_id);setSeek(t.best_frame/clip.fps);}}><strong>#{t.track_id} · {t.class}</strong><span>{t.colour} · {t.dwell_s.toFixed(1)}s visible</span><small>{t.plate.text?maskPlate(t.plate.text,session?.user.role==='viewer'):'Plate: abstained'} · jump to best frame</small></button>)}</div></div></div></>}</div></Panel>;
}

