import { drawDetection } from './DetectionOverlay';
import { useEffect,useRef,useState } from 'react';
import { useRealFootage } from './context';
import { useSession } from '../session';
import { Empty } from '../components/UI';
import SourceBadge from './SourceBadge';
export default function RealVideo({clipId,seek=0,trackId}:{clipId:string;seek?:number;trackId?:number}){
 const {bundle}=useRealFootage(),{session}=useSession(),v=useRef<HTMLVideoElement>(null),canvas=useRef<HTMLCanvasElement>(null),[seconds,setSeconds]=useState(0),[error,setError]=useState('');const clip=bundle?.manifest.clips.find(c=>c.id===clipId),analysis=bundle?.analysis[clipId],counts=bundle?.counts[clipId],viewer=session?.user.role==='viewer';
 useEffect(()=>{const video=v.current;if(!video)return;const go=()=>{video.currentTime=Math.min(seek,video.duration||seek);};if(video.readyState)go();video.addEventListener('loadedmetadata',go);return()=>video.removeEventListener('loadedmetadata',go);},[seek,clipId]);
 useEffect(()=>{const video=v.current,c=canvas.current;if(!video||!c||!analysis||!clip||(!analysis.frames.length&&!counts?.lines.length))return;let raf=0;const draw=()=>{const time=video.currentTime,frame=Math.floor(time*analysis.fps),record=analysis.frames[Math.floor(frame/analysis.frame_stride)];c.width=clip.width;c.height=clip.height;const ctx=c.getContext('2d');if(ctx){ctx.clearRect(0,0,c.width,c.height);ctx.font='15px system-ui';if(record&&Math.abs(record.frame-frame)<=analysis.frame_stride)for(const box of record.detections){drawDetection(ctx,box,c.width,c.height,viewer,box.track_id===trackId);if(box.plate_box){const [a,b,d,e]=box.plate_box;ctx.strokeRect(a*c.width,b*c.height,(d-a)*c.width,(e-b)*c.height);}}
 for(const line of counts?.lines||[]){ctx.strokeStyle='#ffe261';ctx.setLineDash([9,7]);ctx.beginPath();ctx.moveTo(line.start[0]*c.width,line.start[1]*c.height);ctx.lineTo(line.end[0]*c.width,line.end[1]*c.height);ctx.stroke();ctx.setLineDash([]);}}
 raf=requestAnimationFrame(draw);};draw();return()=>cancelAnimationFrame(raf);},[analysis,clip,counts,trackId,viewer]);
 if(!clip)return <Empty title="No real footage bundle loaded" message="Run the offline pipeline to load your recordings."/>;
 if(viewer&&!clip.redacted_video)return <Empty title="Raw footage restricted" message="A redacted preview has not been generated. Viewer access to raw recordings is disabled in this interface."/>;
 const crossed=counts?.crossings.filter(c=>c.video_time_s<=seconds)||[];
 return <div className="real-video"><SourceBadge staged={clip.staged} reviewed={!!clip.evidence}/><div className="real-video-stage" style={{width:`min(100%, ${420*clip.width/clip.height}px)`,marginInline:"auto"}}><video ref={v} src={`/real/${viewer?clip.redacted_video:clip.video}`} poster={clip.evidence?`/real/${clip.evidence.poster}`:undefined} controls muted playsInline preload="metadata" onTimeUpdate={e=>setSeconds(e.currentTarget.currentTime)} onError={()=>setError('The recording could not be loaded.')}/><canvas ref={canvas} aria-hidden="true"/></div>{error&&<p role="alert">{error}</p>}<div className="real-video-caption"><span>{clip.id} · {seconds.toFixed(1)} / {clip.duration_s.toFixed(1)} s</span><span>{clip.evidence?'Reviewed plate crop · continuous tracking not measured':`${crossed.length} line crossings so far`} · {Object.entries(counts?.direction_totals||{}).map(([d])=>`${d}: ${crossed.filter(c=>c.direction===d).length}`).join(' · ')}</span></div><p className="muted">{clip.staged?`Illustrative assignment: ${clip.camera_id} · ${clip.start_ist}. This clip was not filmed at that Delhi location.`:'User-supplied camera placement.'}</p><details><summary>Evidence hash · source file SHA-256</summary><code className="hash-text">SHA-256 {clip.sha256}</code><p>Identifies the source file; does not establish a chain of custody.</p></details></div>;
}
