import { useState } from 'react';
import { Panel,Empty } from '../components/UI';
import NetworkMap from '../components/NetworkMap';
import { cameras,cameraById,roads,routeBetween,normalise,haversine } from '../demo/model';
import type { Trajectory } from '../types';
import type { RealTrajectory } from './types';
import { useRealFootage } from './context';
import RealVideo from './RealVideo';
import SourceBadge from './SourceBadge';
import { record } from '../demo/api';
export function assembleTrajectory(real:RealTrajectory):Trajectory{
 const stops=[...real.stops].filter(s=>cameraById.has(s.camera_id)).sort((a,b)=>a.ts_ist.localeCompare(b.ts_ist));
 const hops=stops.map((s,i)=>{const prev=stops[i-1],r=prev?routeBetween(prev.camera_id,s.camera_id):{distance:0,path:[]},seconds=prev?(Date.parse(s.ts_ist)-Date.parse(prev.ts_ist))/1000:0;return {detection_id:i,camera_id:s.camera_id,camera_name:cameraById.get(s.camera_id)!.name,timestamp:s.ts_ist,confidence:s.confidence,observed_plate:real.plate,leg_distance_km:r.distance,seconds,speed_kmh:null,inferred_cameras:r.path.slice(1,-1),implausible:!!prev&&haversine(cameraById.get(prev.camera_id)!,cameraById.get(s.camera_id)!)/Math.max(1,seconds)*3600>110};});
 return {found:!!stops.length,plate:real.plate,identity_id:0,vehicle_type:'unclassified',hops,total_distance_km:hops.reduce((n,h)=>n+h.leg_distance_km,0),geojson:{type:'LineString',coordinates:stops.map(s=>{const c=cameraById.get(s.camera_id)!;return [c.lon,c.lat];})}};
}
export default function RealJourney(){const {bundle}=useRealFootage(),[query,setQuery]=useState(''),[plate,setPlate]=useState(''),[index,setIndex]=useState(0),[reason,setReason]=useState('Recorded footage evaluation'),[searched,setSearched]=useState(false);const real=bundle?.trajectories.find(t=>t.plate===plate),trajectory=real?assembleTrajectory(real):null,stops=real?[...real.stops].sort((a,b)=>a.ts_ist.localeCompare(b.ts_ist)):[],stop=stops[index];
 const lookup=(value:string)=>{setPlate(normalise(value));setIndex(0);setSearched(true);record('real.trajectory.search',{plate:normalise(value),reason});};
 function exportJourney(){if(!real||!trajectory)return;const blob=new Blob([JSON.stringify({type:'Feature',geometry:trajectory.geojson,properties:{...real,attribution:'Road data © OpenStreetMap contributors (ODbL). Delhi boundary: DataMeet. Camera placements illustrative.'}},null,2)],{type:'application/geo+json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='real-trajectory.geojson';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <Panel title="Track a plate from real footage" subtitle="Only accepted plate reads from the offline pipeline appear here" className="real-source-banner"><div className="padded"><SourceBadge/><form className="filter-bar" onSubmit={e=>{e.preventDefault();lookup(query);}}><label>Plate from recording<input aria-label="Real footage plate" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Enter a measured plate" required/></label><label>Purpose / case reference<input value={reason} required minLength={5} onChange={e=>setReason(e.target.value)}/></label><button className="primary">Track real plate</button>{bundle?.trajectories.map(t=><button type="button" key={t.plate} onClick={()=>{setQuery(t.plate);lookup(t.plate);}}>{t.plate}</button>)}</form>{!real?<Empty title={searched?'No accepted real-footage plate matches':'No accepted real-footage plates yet'} message="The included recordings support vehicle detection, tracking and counting. Readable plate footage and local plate models are required for identity-based trajectories. The synthetic Delhi journeys below remain available for workflow testing."/>:stop&&<><div className="filter-bar"><SourceBadge staged={stop.staged}/><span>{stops.length===1?'Single-stop trajectory':`${stops.length} observed stops · routes between cameras are inferred`}</span><button onClick={exportJourney}>Export GeoJSON</button><button onClick={()=>window.print()}>Print case file</button><button disabled={index===stops.length-1} onClick={()=>setIndex(i=>i+1)}>Jump to next sighting</button></div><div className="two-columns"><NetworkMap cameras={cameras} roads={roads} trajectory={trajectory} progress={stops.length>1?index/(stops.length-1):1} large/><RealVideo clipId={stop.clip_id} seek={stop.video_time_s} trackId={stop.track_id}/></div><div className="real-track-list">{stops.map((s,i)=><button key={`${s.clip_id}-${s.track_id}`} onClick={()=>setIndex(i)}>{i+1}. {s.camera_id} · {s.ts_ist} · vote {(s.confidence*100).toFixed(1)}% · {s.staged?'STAGED PLACEMENT':'recorded placement'}</button>)}</div><p>{bundle?.registry[plate]?'SYNTHETIC REGISTRY · user-provided consented-vehicle entry':'No registry record (connector not configured)'}</p>{bundle?.registry[plate]&&<dl>{Object.entries(bundle.registry[plate]).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{/owner|address|contact|engine|chassis/i.test(k)?'•••• (restricted)':v}</dd></div>)}</dl>}</>}</div></Panel>;
}

