import { useEffect,useState } from 'react';
import { Panel,Empty,Modal,Badge } from '../components/UI';
import { useRealFootage } from './context';
import RealVideo from './RealVideo';
import SourceBadge from './SourceBadge';
import { record } from '../demo/api';
import type { RealEvent } from './types';
export default function RealAlerts(){const {bundle}=useRealFootage(),[selected,setSelected]=useState<RealEvent|null>(null),[workflow,setWorkflow]=useState<Record<string,{status:string;assignee:string;note:string}>>({}),[running,setRunning]=useState(false),[step,setStep]=useState(0);const events=[...(bundle?.events||[])].sort((a,b)=>a.ts_ist.localeCompare(b.ts_ist)),state=selected?workflow[selected.id]||{status:'Open',assignee:'',note:''}:null;
 useEffect(()=>{if(!running||!events.length)return;const timer=setInterval(()=>setStep(i=>{if(i>=events.length-1){setRunning(false);return i;}return i+1;}),3000);return()=>clearInterval(timer);},[running,events.length]);
 return <Panel title="Real-footage alerts" subtitle="Only accepted reads generate identity alerts; placements are disclosed" className="mt-panel"><div className="padded"><SourceBadge/><button disabled={!events.length} onClick={()=>{setStep(0);setRunning(!running);}}>{running?'Stop real-footage scenario':'Run real-footage scenario'}</button>{!events.length?<Empty title="No real identity alerts" message="No accepted plate reads or watchlist hits exist in these sample recordings. Synthetic scenario alerts below are separate."/>:(running?events.slice(0,step+1):events).map(e=><div className="case-note" key={e.id}><SourceBadge staged={e.staged}/><p>{e.plate} · {e.type} · {e.ts_ist}</p><Badge>{workflow[e.id]?.status||'Open'}</Badge><button onClick={()=>setSelected(e)}>Review real evidence</button></div>)}</div>{selected&&state&&<Modal title="Real-footage evidence" onClose={()=>setSelected(null)}><RealVideo clipId={selected.clip_id} seek={selected.video_time_s} trackId={selected.track_id}/><p>{selected.explanation}</p><p>No plate image retained. Evidence is the recording timecode and overlay.</p>{selected.factors.map(f=><div className="stat-pair" key={f.label}><span>{f.label}</span><strong>+{f.points}</strong></div>)}{selected.type==='clone_suspect'&&<div className="real-notice">{selected.distance_km?.toFixed(2)} km ÷ {selected.elapsed_s?.toFixed(1)} s × 3600 = {selected.implied_kmh?.toFixed(1)} km/h. Conservative straight-line lower bound. Human verification required.{selected.sightings?.map(s=><RealVideo key={`${s.clip_id}-${s.track_id}`} clipId={s.clip_id} seek={s.video_time_s} trackId={s.track_id}/>)}</div>}<form className="form-stack" onSubmit={e=>{e.preventDefault();record('real.alert.workflow',{id:selected.id,...state});setSelected(null);}}><label>Status<select value={state.status} onChange={e=>setWorkflow({...workflow,[selected.id]:{...state,status:e.target.value}})}>{['Open','Acknowledged','Verified','Dispatched','Closed','False Positive'].map(s=><option key={s}>{s}</option>)}</select></label><label>Assignee<input value={state.assignee} onChange={e=>setWorkflow({...workflow,[selected.id]:{...state,assignee:e.target.value}})}/></label><label>Review note<textarea value={state.note} onChange={e=>setWorkflow({...workflow,[selected.id]:{...state,note:e.target.value}})}/></label><button className="primary">Save review</button></form></Modal>}</Panel>;
}
