import RealAttributes from '../real/RealAttributes';
import { useMemo, useState } from 'react';
import { Link } from '../router';
import { Search, RotateCcw } from 'lucide-react';
import { Badge, Empty, Page, PageHeader, Panel, Plate } from '../components/UI';
import SimulatedFeed from '../components/SimulatedFeed';
import { cameras, cameraById, colours, reads, vehicles } from '../demo/model';
import { record } from '../demo/api';
import { REGIONS } from '../constants/city';
const defaults={kind:'',colour:'',region:'',camera:'',make:'',confidence:0,availability:'available',reason:''};
export default function Attributes(){const [filters,setFilters]=useState(defaults),[applied,setApplied]=useState(defaults),[page,setPage]=useState(1);
 const results=useMemo(()=>vehicles.filter(v=>(!applied.kind||v.vehicle_type===applied.kind)&&(!applied.colour||v.colour===applied.colour)&&(!applied.make||v.make===applied.make)&&v.confidence>=applied.confidence).flatMap(v=>{const sightings=reads.filter(r=>r.identity_id===v.id&&(!applied.camera||r.camera_id===applied.camera)&&(!applied.region||cameraById.get(r.camera_id)?.region===applied.region));return sightings.length?[{vehicle:v,sighting:sightings.at(-1)!,count:sightings.length}]:[];}),[applied]);
 const pool=applied.availability==='unidentified'?results.filter(r=>r.vehicle.id>4).slice(0,24):results,shown=pool.slice((page-1)*12,page*12);
 const set=(key:keyof typeof defaults,value:string|number)=>setFilters(f=>({...f,[key]:value,...(key==='region'?{camera:''}:{})}));
 function search(next=filters){setApplied({...next});setPage(1);record('attribute.search',next);}
 return <Page><PageHeader title="Attribute search" description="Test searches by colour, class, make, region and camera. Browse uploaded video evidence and the existing synthetic vehicle histories." actions={<Badge tone="amber">{vehicles.length} synthetic vehicles</Badge>}/><div className="demo-disclosure">Try White + Car, Red + Car, or South West Delhi. Uploaded clips use reviewed attributes; existing synthetic examples are labelled separately.</div>
 <Panel title="Find a vehicle" subtitle="Filters combine with AND · blank fields include all values"><form onSubmit={e=>{e.preventDefault();search();}}><div className="filter-bar attribute-filters"><label>Vehicle class<select value={filters.kind} onChange={e=>set('kind',e.target.value)}><option value="">All classes</option>{['car','van','motorcycle','truck','bus'].map(k=><option key={k}>{k}</option>)}</select></label><label>Colour<select value={filters.colour} onChange={e=>set('colour',e.target.value)}><option value="">All colours</option>{colours.map(c=><option key={c}>{c}</option>)}</select></label><label>Make<select value={filters.make} onChange={e=>set('make',e.target.value)}><option value="">All makes</option><option>Maruti Suzuki</option><option>Hyundai</option><option>Peugeot</option><option>Mercedes-Benz</option></select></label><label>Region<select aria-label="Attribute region" value={filters.region} onChange={e=>set('region',e.target.value)}><option value="">All Delhi</option>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></label><label>Camera<select value={filters.camera} onChange={e=>set('camera',e.target.value)}><option value="">All cameras</option>{cameras.filter(c=>!filters.region||c.region===filters.region).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Minimum confidence<select value={filters.confidence} onChange={e=>set('confidence',+e.target.value)}>{[0,.8,.9,.95].map(c=><option key={c} value={c}>{c*100}%</option>)}</select></label><label>Plate availability<select value={filters.availability} onChange={e=>set('availability',e.target.value)}><option value="available">Plate available</option><option value="unidentified">Unidentified sample tracks</option></select></label><label>Additional reason (optional)<input aria-label="Attribute additional reason" value={filters.reason} onChange={e=>set('reason',e.target.value)} placeholder="Optional case reference"/></label><button className="primary"><Search size={15}/>Find vehicles</button><button type="button" onClick={()=>{setFilters(defaults);search(defaults);}}><RotateCcw size={14}/>Reset</button></div></form></Panel>
 <div className="demo-plate-presets"><span>Quick tests</span>{['White','Red','Blue'].map(c=><button key={c} onClick={()=>{const next={...defaults,kind:'car',colour:c};setFilters(next);search(next);}}>{c} cars</button>)}<button onClick={()=>{const next={...defaults,region:'South West Delhi'};setFilters(next);search(next);}}>Airport & Dwarka region</button></div>
 <RealAttributes filters={applied}/>
 <div className="result-heading"><strong>{pool.length} matching {applied.availability==='available'?'vehicles':'unidentified tracks'}</strong><span>Page {page} of {Math.max(1,Math.ceil(pool.length/12))} · grouped by synthetic identity</span></div>
 {shown.length?<div className="attribute-grid">{shown.map(({vehicle:v,sighting:r,count})=><Panel key={v.id}><SimulatedFeed camera={r.camera_id} plate={applied.availability==='available'?v.plate:'UNREADABLE'} compact paused/><div className="padded"><div className="spread"><strong>{v.colour} {v.vehicle_type}</strong><Badge tone={v.confidence>=.9?'green':'amber'}>{Math.round(v.confidence*100)}% synthetic</Badge></div><p className="muted mt-2">{v.make} {v.model} · {count} sightings</p><p className="muted mt-2">{cameraById.get(r.camera_id)?.name} · {cameraById.get(r.camera_id)?.region}</p><div className="mt-panel">{applied.availability==='available'?<Plate value={v.plate}/>:<Badge>Plate unreadable · anonymous sample</Badge>}</div><div className="attribute-actions">{applied.availability==='available'&&<Link className="button primary" to={`/trajectories?plate=${v.plate}`}>Track trajectory</Link>}<button onClick={()=>{const next={...defaults,kind:v.vehicle_type,colour:v.colour};setFilters(next);search(next);}}>Find similar</button></div></div></Panel>)}</div>:<Panel><Empty title="No synthetic vehicles match this combination" message="Try fewer filters, choose a quick test, or reset to browse all 160 vehicles." action={<button onClick={()=>{setFilters(defaults);search(defaults);}}>Reset filters</button>}/></Panel>}
 <div className="pagination"><span>{pool.length} results</span><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={page*12>=pool.length} onClick={()=>setPage(p=>p+1)}>Next</button></div></Page>;
}
