import { useMemo,useState } from 'react';
import { ResponsiveContainer,BarChart,Bar,LineChart,Line,PieChart,Pie,Cell,XAxis,YAxis,Tooltip } from 'recharts';
import { Page,PageHeader,Panel,Modal } from '../components/UI';
import { Link } from '../router';
import { cameras,roads,reads,seeded } from '../demo/model';
import { REGIONS } from '../constants/city';
import { ProvenanceChip } from '../lib/provenance';
import { cameraHealth,type HealthInput } from '../lib/cameraHealth';
import { useStreamMeasurements } from '../real/streamMeasurements';
import { liveFeeds } from '../real/liveFeeds.config';
import { FeedTile,locateCamera } from '../real/LiveFeeds';
import NetworkMap from '../components/NetworkMap';
const issues=['low light','blur','obstruction','tamper suspicion','high latency','packet loss','stalled stream','low read rate'];
const show=(n:number|null|undefined,d=1)=>n==null?'Not measured':n.toFixed(d);
const percent=(n:number|null|undefined)=>n==null?'Not measured':`${(n*100).toFixed(1)}%`;
const modelled=cameras.map((c,i)=>{const rng=seeded(26127+i);return {...c,input:{signal:c.status!=='Maintenance',fps:c.fps,latency:80+rng()*400,brightness:60+rng()*110,sharpness:40+rng()*260,readRate:.5+rng()*.5} as HealthInput,uptime:c.status==='Maintenance'?.72:.95+rng()*.05};});
export default function CameraHealth(){const measured=useStreamMeasurements(),[query,setQuery]=useState(''),[region,setRegion]=useState('All Delhi'),[status,setStatus]=useState('All'),[issue,setIssue]=useState('All'),[grid,setGrid]=useState(false),[sort,setSort]=useState('health'),[selected,setSelected]=useState(''),[copied,setCopied]=useState(false);
 const rows=useMemo(()=>modelled.map(c=>{const feed=liveFeeds.find(f=>f.camera_id===c.id),m=measured[c.id],isMeasured=!!feed;const input:HealthInput=isMeasured?{signal:m?.playing?!m.stalled:null,fps:m?.fps??null,latency:null,brightness:m?.brightness??null,sharpness:m?.sharpness??null,readRate:m?.readRate??null}:c.input;const health=cameraHealth(input);if(isMeasured&&!m)health.issues=[];const observed=reads.filter(r=>r.camera_id===c.id),confidence=isMeasured?m?.ocrConfidence??null:observed.reduce((s,r)=>s+(r.confidence||0),0)/Math.max(1,observed.length);return {...c,input,feed,m,isMeasured,health,confidence};}),[measured]);
 const filtered=rows.filter(c=>(region==='All Delhi'||c.region===region)&&(status==='All'||c.health.status===status)&&(issue==='All'||c.health.issues.includes(issue))&&`${c.id} ${c.name} ${c.region} ${c.lat.toFixed(6)} ${c.lon.toFixed(6)}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='latency'?(b.input.latency??-1)-(a.input.latency??-1):(a.health.total??101)-(b.health.total??101));
 const models=rows.filter(c=>!c.isMeasured),scores=models.map(c=>c.health.total||0),latencies=models.map(c=>c.input.latency||0).sort((a,b)=>a-b),active=rows.find(c=>c.id===selected);
 const byRegion=REGIONS.map(name=>({name,...Object.fromEntries(['Online','Degraded','Offline'].map(s=>[s,models.filter(c=>c.region===name&&c.health.status===s).length]))})),breakdown=issues.map(name=>({name,value:models.filter(c=>c.health.issues.includes(name)).length})).filter(v=>v.value),trend=Array.from({length:24},(_,hour)=>{const rng=seeded(26127+hour);return {hour:`${hour}:00`,health:Math.round(scores.reduce((a,b)=>a+b,0)/Math.max(1,scores.length)-5+rng()*10)};});
 return <Page><PageHeader title="Camera Health Intelligence" description="Review stream quality, camera availability and the locations that need attention."/><ProvenanceChip source="modelled"/><p>Fleet figures below cover {models.length} modelled nodes. The {liveFeeds.length} recorded feeds have separate playback measurements; missing sensor data is not scored.</p><div className="health-kpis">{[['Online',models.filter(c=>c.health.status==='Online').length],['Degraded',models.filter(c=>c.health.status==='Degraded').length],['Offline',models.filter(c=>c.health.status==='Offline').length],['Average health',(scores.reduce((a,b)=>a+b,0)/Math.max(1,scores.length)).toFixed(1)],['Open issues',models.filter(c=>c.health.issues.length).length],['Median latency',`${show(latencies[Math.floor(latencies.length/2)])} ms`],['Unreliable reads',models.filter(c=>c.health.issues.includes('low read rate')).length]].map(([label,value])=><Panel key={label}><div className="padded"><small>{label}</small><h2>{value}</h2></div></Panel>)}</div>
 <Panel title="Camera locations" className="health-map"><NetworkMap cameras={rows.map(c=>({...c,status:c.health.status}))} roads={roads} region={region} onRegion={setRegion} onCamera={c=>setSelected(c.id)} statusColors/></Panel>
 <div className="filter-bar standalone"><label>Search cameras<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ID, locality or coordinates"/></label><label>Region<select value={region} onChange={e=>setRegion(e.target.value)}><option>All Delhi</option>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['All','Online','Degraded','Offline','Unmeasured'].map(s=><option key={s}>{s}</option>)}</select></label><label>Issue<select value={issue} onChange={e=>setIssue(e.target.value)}>{['All',...issues].map(s=><option key={s}>{s}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="health">Health score</option><option value="name">Name</option><option value="latency">Latency</option></select></label><button onClick={()=>setGrid(!grid)}>{grid?'Table':'Card grid'}</button></div>
 {grid?<div className="camera-grid">{filtered.map(c=><Panel key={c.id}><div className="padded"><ProvenanceChip source={c.isMeasured?'measured':'modelled'}/><button onClick={()=>setSelected(c.id)}>{c.id} · {c.name}</button><p>{c.region}</p><p className="mono">{c.lat.toFixed(6)}, {c.lon.toFixed(6)}</p><p>{c.health.status} · {show(c.health.total,0)}</p><dl className="health-card-details"><dt>Last seen</dt><dd>{c.m?new Date(c.m.at).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata'}):c.isMeasured?'Not sampled':'30 Sep 2026'}</dd><dt>Playback / modelled uptime</dt><dd>{percent(c.isMeasured?c.m?.uptime:c.uptime)}</dd><dt>FPS</dt><dd>{show(c.input.fps)}</dd><dt>Network latency</dt><dd>{show(c.input.latency)}</dd><dt>Plate read rate</dt><dd>{percent(c.input.readRate)}</dd><dt>Mean OCR confidence</dt><dd>{percent(c.confidence)}</dd><dt>Issues</dt><dd>{c.health.issues.join(', ')||'None observed'}</dd></dl><Link className="button" to={locateCamera(c.id)}>Locate</Link></div></Panel>)}</div>:<Panel><div className="padded"><ProvenanceChip source="measured"/> Recorded feed rows (C01–C05) · <ProvenanceChip source="modelled"/> Other camera nodes</div><div className="table-scroll"><table><thead><tr>{['Camera / name','Location','Coordinates','Status / health','Last seen','Uptime','FPS','Latency','Plate read rate','Mean OCR confidence','Issues','Locate'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(c=><tr key={c.id} tabIndex={0} onClick={e=>{if(!(e.target as Element).closest('a,button'))setSelected(c.id);}} onKeyDown={e=>{if(e.key==='Enter')setSelected(c.id);}} className={selected===c.id?'selected':''}><td><button onClick={()=>setSelected(c.id)}>{c.id} · {c.name}</button><small>{c.isMeasured?'Recorded feed metrics':'Seeded camera node'}</small></td><td>{c.name} · {c.region}</td><td className="mono">{c.lat.toFixed(6)}, {c.lon.toFixed(6)}</td><td>{c.isMeasured&&!c.m?'Not sampled':c.isMeasured&&!c.m?.playing?'Playback paused':c.health.status} / {show(c.health.total,0)}</td><td>{c.isMeasured?c.m?new Date(c.m.at).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata'}):'Not sampled':'30 Sep 2026'}</td><td>{percent(c.isMeasured?c.m?.uptime:c.uptime)}</td><td>{show(c.input.fps)}</td><td>{show(c.input.latency)}{c.input.latency!=null?' ms':''}</td><td>{percent(c.input.readRate)}</td><td>{percent(c.confidence)}</td><td>{c.health.issues.join(' · ')||'None observed'}</td><td><Link className="button" aria-label={`Locate ${c.id}`} to={locateCamera(c.id)}>⌖</Link></td></tr>)}</tbody></table></div></Panel>}
 <div className="two-columns mt-panel"><Panel title="Status by region" action={<ProvenanceChip source="modelled"/>}><ResponsiveContainer width="100%" height={250}><BarChart data={byRegion}><XAxis dataKey="name" fontSize={9}/><YAxis/><Tooltip/>{['Online','Degraded','Offline'].map((s,i)=><Bar key={s} dataKey={s} stackId="a" fill={['#168f81','#d5983e','#cf6164'][i]} isAnimationActive={false}/>)}</BarChart></ResponsiveContainer></Panel><Panel title="Issue breakdown" action={<ProvenanceChip source="modelled"/>}><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={breakdown} dataKey="value" nameKey="name" innerRadius={60} outerRadius={85} isAnimationActive={false}>{breakdown.map((b,i)=><Cell key={b.name} fill={['#168f81','#d5983e','#cf6164','#829ab7'][i%4]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Panel><Panel title="24-hour fleet health trend" action={<ProvenanceChip source="modelled"/>}><ResponsiveContainer width="100%" height={220}><LineChart data={trend}><XAxis dataKey="hour"/><YAxis domain={[0,100]}/><Tooltip/><Line dataKey="health" stroke="#168f81" isAnimationActive={false}/></LineChart></ResponsiveContainer></Panel><Panel title="Needs attention" action={<ProvenanceChip source="modelled"/>}><div className="padded">{[...models].sort((a,b)=>(a.health.total||0)-(b.health.total||0)).slice(0,6).map(c=><p key={c.id}><button onClick={()=>setSelected(c.id)}>{c.id} · {c.name} · {c.health.total}</button> {c.health.issues.join(', ')}</p>)}</div></Panel></div>
 {active&&<Modal className="camera-health-drawer" title={`${active.id} · ${active.name}`} onClose={()=>setSelected('')}><ProvenanceChip source={active.isMeasured?'measured':'modelled'}/><p>{active.name} · {active.region}</p><p className="mono">{active.lat.toFixed(6)}, {active.lon.toFixed(6)} <button onClick={()=>void navigator.clipboard.writeText(`${active.lat.toFixed(6)}, ${active.lon.toFixed(6)}`).then(()=>setCopied(true)).catch(()=>setCopied(false))}>{copied?'Copied':'Copy coordinates'}</button></p>{Object.entries(active.health.components).map(([name,value])=><div className="stat-pair" key={name}><span>{name}</span><strong>{show(value)}</strong></div>)}<p>Network latency is unavailable from local playback. Plate read rate uses accepted tracks / detected tracks only when an analysis file is loaded; confidence is not accuracy.</p><h3>Issue timeline</h3>{active.m?<><p>Dropped browser frames: {active.m.dropped} · packet loss is not measured.</p>{active.m.history.slice(-8).map((h,i)=><p key={i}>{h.time} · {h.issues.join(', ')||'No quality issues observed'}</p>)}</>:<p>No measured issue timeline available.</p>}<h3>FPS / decoder latency history</h3>{active.m?<ResponsiveContainer width="100%" height={140}><LineChart data={active.m.history}><XAxis dataKey="time" hide/><Tooltip/><Line dataKey="fps" stroke="#168f81" isAnimationActive={false}/><Line dataKey="latency" stroke="#d5983e" isAnimationActive={false}/></LineChart></ResponsiveContainer>:<p>No playback samples recorded yet.</p>}<p>Plate read rate history: Not measured.</p>{active.feed&&<FeedTile feed={active.feed} expanded/>}<div className="flex gap-2"><Link className="button primary" to={locateCamera(active.id)}>Locate</Link><Link className="button" to="/live">View live</Link><Link className="button" to={`/trajectories?camera=${active.id}`}>Open trajectories</Link><button onClick={()=>setSelected('')}>Close</button></div></Modal>}
 </Page>;
}
