import RealWorkspace from '../real/RealWorkspace';
import { useRef, useState } from 'react';
import { Link } from '../router';
import { Maximize, Pause, Play } from 'lucide-react';
import { Badge, Page, PageHeader, Panel, Plate } from '../components/UI';
import SimulatedFeed from '../components/SimulatedFeed';
import NetworkMap from '../components/NetworkMap';
import { cameras, roads, reads, densityAt, cameraById } from '../demo/model';
import { useDemo } from '../demo/context';
import { REGIONS } from '../constants/city';
import { useData } from '../data';

export default function Live({wall=false}:{wall?:boolean}){const {region,setRegion,tick,running,start,stop,elapsed}=useDemo(),d=useData(),[paused,setPaused]=useState(false),[mode,setMode]=useState('Recorded traffic samples'),container=useRef<HTMLDivElement>(null);const scoped=cameras.filter(c=>region==='All Delhi'||c.region===region),offset=Math.floor(tick/10)%Math.max(1,scoped.length),selected=Array.from({length:4},(_,i)=>scoped[(offset+i)%scoped.length]),recent=reads.filter(r=>region==='All Delhi'||cameraById.get(r.camera_id)?.region===region),ticker=Array.from({length:10},(_,i)=>recent[(recent.length-1-Math.floor(tick/3)-i+recent.length*100)%recent.length]);
 const full=()=>{if(document.fullscreenElement)void document.exitFullscreen();else void container.current?.requestFullscreen().catch(()=>{});};
 return <div ref={container} className={wall?'control-wall':''}><Page><PageHeader title={wall?'Control room wall':'Live monitoring'} description="Recorded traffic footage with pipeline overlays, alongside synthetic Delhi camera scenarios." actions={<><button onClick={full}><Maximize size={15}/>Full screen</button><button className="primary" onClick={running?stop:start}>{running?<Pause size={15}/>:<Play size={15}/>} {running?`Stop scenario · ${elapsed}s`:'Run demo scenario'}</button>{wall&&<Link className="button" to="/live">Exit wall</Link>}</>}/><div className="filter-bar standalone"><label>Region<select value={region} onChange={e=>setRegion(e.target.value)}><option>All Delhi</option>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></label><label>Feed type<select value={mode} onChange={e=>setMode(e.target.value)}><option>Simulated Delhi CCTV</option><option>Recorded traffic samples</option></select></label><button onClick={()=>setPaused(!paused)}>{paused?'Resume feeds':'Pause feeds'}</button><Badge tone={mode==='Recorded traffic samples'?'green':'amber'}>{mode==='Recorded traffic samples'?'Recorded footage · model output':'SYNTHETIC camera feeds'}</Badge>{!wall&&<Link className="button" to="/wall">Open control room wall</Link>}</div>
 {mode==='Recorded traffic samples'?<RealWorkspace/>:<div className={wall?'wall-layout':'live-layout'}>{wall&&<Panel title="Delhi network" subtitle="Simulated traffic density"><NetworkMap cameras={cameras} roads={roads} density={densityAt(9,region)} region={region} onRegion={setRegion} heat large/></Panel>}<div className="live-camera-grid">{selected.map((c,i)=><Panel key={c.id}><SimulatedFeed camera={c.id} plate={['DL01AB1234','RJ14CB2210','UP16AX9912','DL08CX9090'][i]} compact paused={paused}/><div className="feed-link"><Badge tone={c.status==='Online'?'green':'amber'}>{c.status} · synthetic</Badge><Link to={`/trajectories?plate=${['DL01AB1234','RJ14CB2210','UP16AX9912','DL08CX9090'][i]}`}>Track this synthetic plate →</Link></div></Panel>)}</div></div>}
 <div className="two-columns mt-panel"><Panel title="Simulated plate-read ticker" subtitle="Historical demo reads rotate every 3 seconds; timestamps remain recorded times"><div className="ticker-list" aria-live="off">{ticker.map((r,i)=><div key={i}><Plate value={r.plate}/><span>{cameraById.get(r.camera_id)?.name}</span><time>{new Date(r.timestamp).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour12:false})} IST</time></div>)}</div></Panel><Panel title="Latest scenario alerts" subtitle="Scripted events for operator workflow testing"><div className="padded">{d.alerts.slice(0,3).map(a=><div className="case-note" key={a.id}><Badge tone="amber">{a.kind}</Badge><p>{a.explanation}</p><Link className="text-link" to="/alerts">Review {a.plate} →</Link></div>)}</div></Panel></div></Page></div>;
}

