import { ProvenanceChip } from '../lib/provenance';
import { Activity, ArrowRight, CarFront, Camera, Fingerprint, Gauge, Play, Route, ShieldAlert, ShieldCheck, RefreshCw } from 'lucide-react';
import { Link } from '../router';
import { useData } from '../data';
import { useSession } from '../session';
import { useDemo } from '../demo/context';
import { cameras, cameraById, reads, densityAt, corridorsAt } from '../demo/model';
import { Badge, Count, Empty, ErrorMessage, Loading, Page, PageHeader, Panel, Plate, ViewLink } from '../components/UI';
import NetworkMap from '../components/NetworkMap';
import { VolumeChart } from '../components/Charts';
import { clock, label, number } from '../utils';

export default function Overview(){const demo=useDemo(),d=useData(),{session}=useSession();const region=demo.region,scopedReads=reads.filter(r=>region==='All Delhi'||cameraById.get(r.camera_id)?.region===region),scopedCameras=cameras.filter(c=>region==='All Delhi'||c.region===region),scopedAlerts=d.alerts.filter(a=>region==='All Delhi'||cameraById.get(a.camera_id)?.region===region);const summary=region==='All Delhi'?d.analytics?.summary:{...d.analytics?.summary,detections:scopedReads.length,unique_vehicles:new Set(scopedReads.map(r=>r.plate)).size,active_cameras:scopedCameras.filter(c=>c.status!=='Maintenance').length,network_average_speed_kmh:32.6};const open=scopedAlerts.filter(a=>a.status!=='Closed').length;const congestion=d.analytics?.corridors.filter(c=>c.congestion_index).map(c=>c.congestion_index!)||[];const mean=congestion.length?congestion.reduce((a,b)=>a+b,0)/congestion.length:null;

  const cards=[{label:'Vehicle sightings',value:summary?.detections,icon:CarFront,note:'Across retained observations'}, {label:'Unique identities',value:summary?.unique_vehicles,icon:Fingerprint,note:'Resolved registration plates'}, {label:'Active camera nodes',value:summary?.active_cameras,icon:Camera,note:'Mapped cameras in selected region',unit:`/ ${scopedCameras.length}`}, {label:'Alerts for review',value:session?.user.role==='viewer'?summary?.open_alerts:open,icon:ShieldAlert,note:'Requires officer verification'}, {label:'Average network speed',value:summary?.network_average_speed_kmh,icon:Gauge,note:'Plausible observed legs',unit:'km/h'}, {label:'Congestion index',value:mean==null?null:Math.round(mean*100)/100,icon:Activity,note:'Mean of measured corridors',unit:'×'}];
  return <Page><PageHeader title="Network overview" description="A connected view of the city. Every sighting adds to the picture." actions={<><button className="secondary icon-button" onClick={()=>void d.reload()} title="Refresh data" aria-label="Refresh data"><RefreshCw size={16}/></button>{session?.user.role==='admin'&&<button className="primary" onClick={demo.start} ><Play size={14}/>Run scenario</button>}</>}/>{d.error&&<ErrorMessage message={d.error} retry={()=>void d.reload()}/>}<div className="overview-context"><span><span className="status-dot"/>Delhi <span className="separator">/</span> {region}</span><span>All retained observations <span className="separator">·</span> IST (UTC+05:30)</span></div><ProvenanceChip source="modelled"/><div className="kpi-grid">{cards.map((c,i)=><section className="kpi-card" key={c.label}><div className="kpi-label">{c.label}<c.icon size={16}/></div><div className="kpi-value"><Count value={c.value}/>{c.unit&&<small>{c.unit}</small>}</div><div className="kpi-note"><span className={`kpi-marker marker-${i}`}/>{c.note}</div></section>)}</div>
  {d.loading?<Loading/>:<><div className="overview-main"><Panel source="modelled" title="Camera network" subtitle="DELHI NCR · GEOGRAPHIC SCHEMATIC" action={<ViewLink to="/map">Explore map</ViewLink>}><NetworkMap cameras={d.cameras} roads={d.roads} density={densityAt(9,region)} corridors={corridorsAt(9)} region={region} onRegion={demo.setRegion}/><div className="map-legend">{['free','moderate','heavy','congested'].map(level=><span key={level}><i className={level}/>{label(level)}</span>)}<small>Toggle Heatmap to show modelled density</small></div></Panel><Panel source="modelled" title="Recent alerts" subtitle="Explainable events, ready for review" action={<Badge tone="blue">{open} open</Badge>} className="recent-alerts">{session?.user.role==='viewer'?<Empty title="Officer access required" message="Vehicle alerts are restricted to authorised officers."/>:scopedAlerts.length?<div className="alert-items">{scopedAlerts.slice(0,4).map(a=><Link to={`/search?q=${a.plate}`} key={a.id} className="alert-item"><div className="alert-item-top"><Badge tone={a.severity==='HIGH'?'red':'amber'}>{label(a.kind)}</Badge><time>{clock(a.timestamp)}</time></div><Plate value={a.plate}/><p>{a.explanation}</p><div className="alert-item-bottom"><span><Camera size={11}/>{a.camera_id}</span><span>Review vehicle <ArrowRight size={12}/></span></div></Link>)}</div>:<Empty title="No alerts to review"/>}<div className="panel-footer"><ViewLink to="/alerts">Open alert workspace</ViewLink></div></Panel></div>
  <div className="overview-bottom"><Panel source="modelled" title="Traffic volume" subtitle="Sightings by hour · IST" action={<ViewLink to="/analytics">Analytics</ViewLink>}>{d.analytics?.vehicles_per_minute.length?<VolumeChart minutes={Array.from({length:24},(_,hour)=>({camera_id:region,minute:new Date(`2026-09-30T${String(hour).padStart(2,'0')}:00:00+05:30`).toISOString(),count:densityAt(hour,region).reduce((sum,d)=>sum+d.count,0)}))}/>:<Empty/>}<div className="chart-footnote">Modeled daily counts. Open Trends to compare two sample dates.</div></Panel><Panel source="modelled" title="Busiest camera nodes" subtitle="Sightings across the retained dataset" action={<Camera size={16} className="muted"/>}><div className="density-list">{d.density.filter(c=>region==='All Delhi'||cameraById.get(c.camera_id)?.region===region).slice(0,5).map((c,i)=><Link to="/map" key={c.camera_id} className="density-row"><span className="rank">0{i+1}</span><div><strong>{c.name}</strong><div className="density-bar"><span style={{width:`${c.count/Math.max(1,d.density[0]?.count)*100}%`}}/></div></div><span className="mono">{number(c.count)}</span></Link>)}</div></Panel><Panel source="modelled" title="Network assurance" subtitle="Evidence and observation status"><div className="assurance-row"><span className="assurance-icon"><ShieldCheck size={19}/></span><div><strong>{d.integrity?.valid?'modelled dataset loaded':'Verification required'}</strong><small>{number(d.integrity?.checked)} modelled detection events</small></div></div><div className="assurance-row"><span className="assurance-icon"><Route size={19}/></span><div><strong>Road topology available</strong><small>40 nodes connected by 65 corridors</small></div></div><div className="assurance-row"><span className="assurance-icon"><Camera size={19}/></span><div><strong>Recorded observations</strong><small>Camera hardware health is not monitored</small></div></div><div className="assurance-note">modelled data supports evaluation. All alerts require human review.</div></Panel></div></>}
  </Page>;
}
