import RegistryCard from '../real/RegistryCard';
import { useCallback, useEffect, useState } from 'react';
import { useLocation, useParams, Link } from '../router';
import { ArrowLeft, Download, LockKeyhole, ShieldPlus, Route, Play, Pause, Camera, FileText, CheckCircle2, AlertTriangle } from 'lucide-react';
import { api } from '../api';
import { useData } from '../data';
import { Badge, Empty, ErrorMessage, Loading, Page, Panel, Plate } from '../components/UI';
import NetworkMap from '../components/NetworkMap';
import type { Owner, Profile as ProfileData } from '../types';
import { date, label, number, splitTrips } from '../utils';

export default function Profile(){const {id}=useParams(),location=useLocation(),data=useData();const [reason,setReason]=useState((location.state as {reason?:string}|null)?.reason||''),[accepted,setAccepted]=useState((location.state as {reason?:string}|null)?.reason||''),[profile,setProfile]=useState<ProfileData|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('Overview'),[owner,setOwner]=useState<Owner|null>(null),[unmaskReason,setUnmaskReason]=useState(''),[showUnmask,setShowUnmask]=useState(false),[note,setNote]=useState(''),[challanStatus,setChallanStatus]=useState('All'),[camera,setCamera]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(1),[speed,setSpeed]=useState(1);
  const load=useCallback(async()=>{if(!accepted)return;setBusy(true);setError('');try{setProfile(await api<ProfileData>(`vehicles/${id}/profile`,{reason:accepted}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[id,accepted]);
  useEffect(()=>{setOwner(null);void load();},[load]);
  useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setProgress(p=>Math.min(1,p+.006*speed)),100);return()=>clearInterval(timer);},[playing,speed]);
  useEffect(()=>{if(progress>=1)setPlaying(false);},[progress]);
  async function unmask(e:React.FormEvent){e.preventDefault();setError('');try{setOwner(await api<Owner>(`vehicles/${id}/owner`,{reason:unmaskReason}));setShowUnmask(false);setUnmaskReason('');}catch(e){setError((e as Error).message);}}
  async function watch(){if(!profile)return;try{await api('watchlist',{plate:profile.identity.plate,reason:accepted});await load();}catch(e){setError((e as Error).message);}}
  async function addNote(e:React.FormEvent){e.preventDefault();try{await api(`vehicles/${id}/notes`,{reason:note});setNote('');await load();}catch(e){setError((e as Error).message);}}
  if(!accepted)return <Page><Panel title="Authorised access required"><form className="padded form-stack" onSubmit={e=>{e.preventDefault();setAccepted(reason);}}><label>Reason for opening this vehicle profile<input value={reason} minLength={5} required onChange={e=>setReason(e.target.value)} placeholder="Enter a case reference or reason"/></label><button className="primary">Open profile</button></form></Panel></Page>;
  if(busy&&!profile)return <Loading label="Reconstructing vehicle profile…"/>;
  if(!profile)return <ErrorMessage message={error||'Profile not found'} retry={()=>void load()}/>;
  const {identity,trajectory,registry}=profile,shownOwner=owner||registry.owner,registration=registry.registration;
  const sightings=trajectory.hops.filter(h=>(!camera||h.camera_id===camera)&&(!from||h.timestamp.slice(0,10)>=from)&&(!to||h.timestamp.slice(0,10)<=to));
  const challeng=registry.challans.filter(c=>challanStatus==='All'||c.status===challanStatus);
  const tabs=['Overview','Sightings','Trajectory','Evidence','Challans','Case notes','Registry record'];
  return <Page><div className="profile-breadcrumb"><Link to="/search"><ArrowLeft size={14}/>Vehicle search</Link><span>/</span>Vehicle profile</div>{error&&<ErrorMessage message={error}/>}<div className="profile-header"><div className="vehicle-icon"><Camera size={29}/></div><div className="profile-heading"><div className="eyebrow">VEHICLE PROFILE · ID {identity.id.toString().padStart(5,'0')}</div><h1><Plate value={identity.plate}/></h1><div className="profile-tags"><Badge tone="blue">{identity.valid?'Valid plate format':'Unvalidated plate'}</Badge><Badge>{label(identity.vehicle_type)}</Badge>{profile.watchlisted&&<Badge tone="amber">Watchlisted</Badge>}<span className="muted">{trajectory.hops.length} sightings · {profile.alerts.length} alerts</span></div></div><div className="profile-actions"><button onClick={()=>{setTab('Overview');setTimeout(()=>window.print(),100);}}><Download size={15}/>Export case file / PDF</button><button onClick={()=>void watch()} disabled={profile.watchlisted}><ShieldPlus size={15}/>{profile.watchlisted?'On watchlist':'Add to watchlist'}</button><button className="primary" onClick={()=>setTab('Trajectory')}><Route size={15}/>Open trajectory</button></div></div>
  <div className="profile-confidence"><CheckCircle2 size={16}/><strong>{Math.round(profile.confidence*100)}% identity confidence</strong><span>Minimum read confidence across all observed hops. Not a calibrated identity probability.</span><Badge tone={profile.integrity.valid?'green':'red'}>{profile.integrity.valid?'Simulated evidence':'Integrity failure'}</Badge></div><div className="tabs no-print" role="tablist">{tabs.map(t=><button role="tab" aria-selected={tab===t} key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}{t==='Sightings'&&<small>{trajectory.hops.length}</small>}{t==='Challans'&&<small>{registry.challans.length}</small>}</button>)}</div>
  {registry.demo&&<div className="demo-disclosure"><FileText size={15}/>Registry, owner and challan records below are consistent synthetic records. No connection to VAHAN or e-Challan.</div>}
  {tab==='Overview'&&<><div className="profile-grid"><Panel title="Registration details" subtitle={registry.demo?'SYNTHETIC REGISTRY · DEMO DATA':'Registry adapter'} action={<Badge>{registry.provider}</Badge>}>{registration?<dl className="details-grid">{Object.entries(registration).map(([key,value])=><div key={key}><dt>{label(key)}</dt><dd>{value}{key.endsWith('until')&&value<new Date().toISOString().slice(0,10)&&<Badge tone="amber">Expired</Badge>}</dd></div>)}</dl>:<Empty title="Registry not connected" message="An authorised government registry provider is required."/>}</Panel><Panel title="Registered owner" subtitle="Protected personal information" action={<LockKeyhole size={16}/>}><div className="padded">{shownOwner?<dl className="owner-details">{Object.entries(shownOwner).map(([key,value])=><div key={key}><dt>{label(key)}</dt><dd>{value}</dd></div>)}</dl>:<p className="muted">Owner data unavailable.</p>}<div className="owner-notice"><LockKeyhole size={14}/>{owner?'Unmasked for this view. Access has been audited.':'Details are masked by default. Unmasking is audited.'}</div>{!owner&&<button className="full-width" onClick={()=>setShowUnmask(true)} disabled={!shownOwner}>Request access to owner details</button>}{owner&&<button onClick={()=>setOwner(null)}>Mask details again</button>}{showUnmask&&<form className="form-stack mt-panel" onSubmit={unmask}><label>Reason for unmasking<input autoFocus required minLength={5} maxLength={400} value={unmaskReason} onChange={e=>setUnmaskReason(e.target.value)}/></label><button className="primary">Unmask and record access</button><button type="button" onClick={()=>setShowUnmask(false)}>Cancel</button></form>}</div></Panel></div><div className="profile-grid mt-panel"><Panel title="Journey at a glance" subtitle={`${number(trajectory.total_distance_km)} km across the inferred road route`}><NetworkMap cameras={data.cameras} roads={data.roads} trajectory={trajectory} density={data.density}/></Panel><Panel title="Behaviour & alert summary" subtitle="Based on retained observed sightings"><div className="padded"><div className="stat-pair"><span>Recorded trips</span><strong>{splitTrips(trajectory.hops).length}</strong></div><div className="stat-pair"><span>Camera nodes visited</span><strong>{new Set(trajectory.hops.map(h=>h.camera_id)).size}</strong></div><div className="stat-pair"><span>Kinematic anomalies</span><strong>{trajectory.hops.filter(h=>h.implausible).length}</strong></div>{profile.alerts.map(a=><div className="explanation" key={a.id}><Badge tone={a.severity==='HIGH'?'red':'amber'}>{label(a.kind)}</Badge><p>{a.explanation}</p></div>)}{!profile.alerts.length&&<p className="muted">No alert history for this identity.</p>}</div></Panel></div></>}
  {tab==='Sightings'&&<Panel title="Sightings by date & time" subtitle="Observed detections only · timestamps displayed in IST"><div className="filter-bar"><label>Camera node<select value={camera} onChange={e=>setCamera(e.target.value)}><option value="">All camera nodes</option>{data.cameras.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>From (UTC date)<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To (UTC date)<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>{sightings.length?<div className="table-scroll"><table><thead><tr><th>Timestamp · IST</th><th>Camera node</th><th>Plate read</th><th>Read confidence</th><th>Lane / direction</th></tr></thead><tbody>{sightings.map(h=><tr key={h.detection_id}><td>{date(h.timestamp)}</td><td>{h.camera_id} · {h.camera_name}</td><td><Plate value={h.observed_plate}/></td><td>{Math.round(h.confidence*100)}%</td><td className="muted">Not captured</td></tr>)}</tbody></table></div>:<Empty title="No sightings in this range"/>}</Panel>}
  {tab==='Trajectory'&&<><Panel title="Trajectory playback" subtitle="Solid: directly connected observations · dashed: inferred camera segments"><NetworkMap cameras={data.cameras} roads={data.roads} trajectory={trajectory} progress={progress} large/><div className="playback"><button className="primary icon-button" aria-label={playing?'Pause trajectory':'Play trajectory'} onClick={()=>{if(progress>=1)setProgress(0);setPlaying(!playing);}}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><input type="range" aria-label="Trajectory position" min="0" max="1" step=".001" value={progress} onChange={e=>{setPlaying(false);setProgress(Number(e.target.value));}}/><span>{Math.round(progress*100)}%</span><select aria-label="Playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,2,4,8].map(s=><option key={s} value={s}>{s}×</option>)}</select></div></Panel><div className="profile-grid mt-panel"><Panel title="Observed hops" subtitle="Distance and speed are road-graph estimates"><div className="hop-list">{trajectory.hops.map((h,i)=><div className="hop-item" key={h.detection_id}><span>{i+1}</span><div><time>{date(h.timestamp)} IST</time><h3>{h.camera_name}</h3><p>{Math.round(h.confidence*100)}% read confidence · {h.leg_distance_km} km · {h.speed_kmh??'—'} km/h</p>{h.inferred_cameras.length>0&&<small>Inferred via {h.inferred_cameras.join(' → ')} · unobserved</small>}{h.implausible&&<div className="anomaly"><AlertTriangle size={13}/>Implausible travel above 110 km/h. Possible plate cloning.</div>}</div></div>)}</div></Panel><Panel title="Trips & dwell time" subtitle="A new trip begins after a gap greater than 30 minutes"><div className="padded">{splitTrips(trajectory.hops).map((trip,i)=><div className="trip-card" key={i}><Badge>Trip {i+1}</Badge><h3>{trip[0].camera_name} → {trip.at(-1)!.camera_name}</h3><p>{trip.length} hops · {number(trip.slice(1).reduce((sum,h)=>sum+h.leg_distance_km,0))} km · {Math.round((+new Date(trip.at(-1)!.timestamp)-+new Date(trip[0].timestamp))/60000)} min</p></div>)}</div></Panel></div></>}
  {tab==='Evidence'&&<div className="evidence-grid">{profile.evidence.map((e,i)=><Panel key={e.id} title={`Hop ${i+1} · ${e.camera_id}`} subtitle={date(e.timestamp)+' IST'} action={<Badge tone="blue">{label(e.resolution.method)}</Badge>}><div className="snapshot-placeholder"><Camera size={30}/><strong>No image retained</strong><span>{e.source==='simulator'?'Synthetic OCR frames; no physical camera crop.':'Image evidence was not stored with this event.'}</span></div><div className="padded"><Plate value={e.plate}/><p className="evidence-description">Voted from {e.reads.length} reads with {Math.round(e.confidence*100)}% confidence. Resolution score {e.resolution.score}. {trajectory.hops[i]?.implausible?'Travel is physically implausible.':'No impossible-travel leg detected.'}</p><details><summary>Inspect per-frame OCR reads</summary><table><thead><tr><th>Raw text</th><th>OCR</th><th>Quality</th></tr></thead><tbody>{e.reads.map((r,j)=><tr key={j}><td className="mono">{r.text}</td><td>{Math.round(r.confidence*100)}%</td><td>{Math.round(r.quality*100)}%</td></tr>)}</tbody></table></details></div></Panel>)}</div>}
  {tab==='Challans'&&<Panel title="Challan records" subtitle="Synthetic records only · not official enforcement data" action={<select aria-label="Challan status" value={challanStatus} onChange={e=>setChallanStatus(e.target.value)}>{['All','Pending','Paid','Disputed','Court'].map(s=><option key={s}>{s}</option>)}</select>}><div className="challan-totals"><span>Pending <strong>₹{number(registry.challans.filter(c=>c.status==='Pending').reduce((s,c)=>s+c.amount,0))}</strong></span><span>Paid <strong>₹{number(registry.challans.filter(c=>c.status==='Paid').reduce((s,c)=>s+c.amount,0))}</strong></span></div><div className="table-scroll"><table><thead><tr><th>Challan number</th><th>Date · IST</th><th>Violation</th><th>Location</th><th>Amount</th><th>Status</th></tr></thead><tbody>{challeng.map(c=><tr key={c.number}><td className="mono">{c.number}</td><td>{date(c.timestamp)}</td><td>{c.violation}</td><td>{c.location}</td><td>₹{number(c.amount)}</td><td><Badge tone={c.status==='Paid'?'green':'amber'}>{c.status}</Badge></td></tr>)}</tbody></table>{!challeng.length&&<Empty title="No challans match this filter"/>}</div></Panel>}
  {tab==='Case notes'&&<Panel title="Linked case notes" subtitle="Notes are stored with this identity and attributed to the signed-in officer"><form className="padded form-stack" onSubmit={addNote}><label>Investigation note<textarea required minLength={5} maxLength={400} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record an observation or next action…"/></label><button className="primary">Save case note</button></form><div className="padded">{profile.notes.map(n=><article className="case-note" key={n.id}><strong>{n.username}</strong><time>{date(n.timestamp)}</time><p>{n.note}</p></article>)}{!profile.notes.length&&<Empty title="No case notes yet" message="Add an observation to begin the case record."/>}</div></Panel>}
  <div className="print-only"><h2>Case file · {identity.plate}</h2><p>Demo record consistency: {profile.integrity.valid?'VERIFIED':'FAILED'} · checked {profile.integrity.checked} events</p><p>Demo marker: {profile.integrity.head}</p><p>Export reason: {accepted}. Registry / owner / challan data are synthetic records.</p>{trajectory.hops.map(h=><p key={h.detection_id}>{date(h.timestamp)} IST — {h.camera_name}, confidence {h.confidence}, leg {h.leg_distance_km} km, {h.speed_kmh??'—'} km/h.</p>)}</div>
  {tab==='Registry record'&&<RegistryCard plate={identity.plate} unmasked={!!owner}/>}</Page>;
}
