import { useEffect, useState } from 'react';
import { Search as SearchIcon, ArrowUpRight, ShieldCheck } from 'lucide-react';
import { useNavigate, useSearchParams } from '../router';
import { api } from '../api';
import type { Vehicle } from '../types';
import { Badge, Empty, ErrorMessage, Loading, Page, PageHeader, Panel, Plate } from '../components/UI';
import { date, number } from '../utils';

export default function Search(){const [params]=useSearchParams(),navigate=useNavigate(),[query,setQuery]=useState(params.get('q')||''),[purpose,setPurpose]=useState('Traffic investigation'),[reason,setReason]=useState(''),[results,setResults]=useState<Vehicle[]|null>(null),[total,setTotal]=useState(0),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{setQuery(params.get('q')||'');setResults(null);setPage(1);},[params]);
  const fullReason=`${purpose}: ${reason.trim()}`;
  async function search(nextPage=1){setBusy(true);setError('');try{const result=await api<{items:Vehicle[];total:number}>('vehicles/search',{query,reason:fullReason,page:nextPage});setResults(result.items);setTotal(result.total);setPage(nextPage);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Page><PageHeader eyebrow="INVESTIGATION WORKSPACE" title="Vehicle search" description="Resolve a registration. Follow the evidence across camera nodes."/><Panel title="Search vehicle identities" subtitle="Indian plate formats · look-alike correction · partial and fuzzy matching"><form className="search-workspace" onSubmit={e=>{e.preventDefault();void search();}}><label className="wide-label">Registration number<div className="input-with-icon"><SearchIcon size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} placeholder="e.g. DL01AB1234 or partial plate" maxLength={40}/></div></label><div className="form-grid"><label>Reason for search<select value={purpose} onChange={e=>setPurpose(e.target.value)}><option>Traffic investigation</option><option>Authorised case review</option><option>Incident response</option><option>System evaluation</option></select></label><label>Case reference / additional reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Enter a case reference or justification" minLength={5} maxLength={300} required/></label></div><div className="form-footer"><span><ShieldCheck size={14}/>Every search is recorded in the audit log.</span><button className="primary" disabled={busy||reason.trim().length<5}><SearchIcon size={16}/>{busy?'Resolving…':'Search vehicles'}</button></div></form></Panel>{error&&<ErrorMessage message={error}/>}<Panel title={results?`Search results · ${total} identities`:'Your investigation starts here'} subtitle="A search match is a candidate identity, not a confirmed legal identification." className="mt-panel">{busy?<Loading/>:results===null?<Empty title="Search by a full or partial plate" message="Try DL01AB1234 for a watchlisted route or DL08CX9090 for the plate-cloning scenario. Leave the plate empty to browse authorised records."/>:results.length?<><div className="table-scroll"><table><thead><tr><th>Registration</th><th>Vehicle class</th><th>Read confidence</th><th>Sightings</th><th>Last sighting · IST</th><th>Match</th><th/></tr></thead><tbody>{results.map(v=><tr key={v.id}><td><Plate value={v.plate}/></td><td>{v.vehicle_type}</td><td>{Math.round(v.confidence*100)}%</td><td className="mono">{number(v.sightings)}</td><td>{date(v.last_seen)}</td><td><Badge tone={v.match_distance===0?'blue':'neutral'}>{v.match_distance===0?'Exact / browse':`Fuzzy · ${v.match_distance}`}</Badge></td><td><button className="text-link" onClick={()=>navigate(`/vehicles/${v.id}`,{state:{reason:fullReason}})}>Open profile<ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div><div className="pagination"><span>{total} results · page {page}</span><button disabled={page===1} onClick={()=>void search(page-1)}>Previous</button><button disabled={page*20>=total} onClick={()=>void search(page+1)}>Next</button></div></>:<Empty title="No matching identities" message="Check the registration, shorten the query or run a simulation from Overview."/>}</Panel></Page>;
}
