import { useState } from 'react';
import { ArrowRight, Eye, EyeOff, LockKeyhole, ShieldCheck, ChevronDown, Network } from 'lucide-react';
import { motion, useReducedMotion } from 'framer-motion';
import { useSession } from '../session';
import { ErrorMessage, Logo } from '../components/UI';

export default function SignIn(){const {config,login,error:connectionError}=useSession();const [username,setUsername]=useState('admin'),[password,setPassword]=useState('demo'),[unit,setUnit]=useState('All Delhi'),[factor,setFactor]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const reduced=useReducedMotion();
  async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{await login(username,password,unit,factor);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="signin"><section className="signin-story"><Logo/><div className="signin-network" aria-hidden="true"><svg viewBox="0 0 640 470"><defs><pattern id="login-grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="#536f98" strokeOpacity=".15"/></pattern></defs><rect width="640" height="470" fill="url(#login-grid)"/>{[[90,200,225,90],[90,200,255,285],[225,90,435,145],[225,90,255,285],[255,285,435,145],[435,145,520,310],[255,285,520,310],[255,285,370,405],[520,310,370,405]].map(([x,y,xx,yy],i)=><g key={i}><line x1={x} y1={y} x2={xx} y2={yy} stroke="#718fba" strokeWidth="1" opacity=".5"/>{!reduced&&<circle r="3" fill="#c1d8f8"><animateMotion dur={`${6+i}s`} repeatCount="indefinite" path={`M${x},${y} L${xx},${yy}`}/></circle>}</g>)}{[[90,200],[225,90],[255,285],[435,145],[520,310],[370,405]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="20" stroke="#749ad3" fill="#1e314d"/><circle cx={x} cy={y} r="6" fill="#afcaf2"/><text x={x+27} y={y+4} fill="#93abc9" fontSize="10" fontFamily="monospace">CAM 0{i+1}</text></g>)}</svg></div><div className="signin-copy"><span className="eyebrow">CLARITY ACROSS EVERY CORRIDOR</span><h1>A city in motion.<br/><span>A clearer picture.</span></h1><p>Connect sightings. Reconstruct journeys.<br/>Turn traffic data into informed decisions.</p><div className="signin-benefits"><span><Network size={16}/>City-wide intelligence</span><span><ShieldCheck size={16}/>Auditable evidence</span></div></div><footer>SIH 2026 <span>/</span> SIH26127 <span>/</span> BEL PROBLEM STATEMENT</footer></section>
    <section className="signin-form-area"><motion.div className="signin-card" initial={{opacity:0,y:reduced?0:12}} animate={{opacity:1,y:0}}><div className="signin-icon"><LockKeyhole size={22}/></div><div className="eyebrow">SECURE COMMAND CENTRE</div><h2>Welcome to CityTrace</h2><p>Sign in to your unit’s intelligence workspace.</p>{(error||connectionError)&&<ErrorMessage message={error||connectionError}/>}<form onSubmit={submit}><label>User ID<input autoComplete="username" placeholder="Enter your User ID" value={username} onChange={e=>setUsername(e.target.value)} maxLength={80}/></label><label>Password<div className="password-field"><input type={show?'text':'password'} autoComplete="current-password" placeholder="Enter your password" value={password} onChange={e=>setPassword(e.target.value)} maxLength={128}/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><label>Unit / Region<select value={unit} onChange={e=>setUnit(e.target.value)}>{(config?.units||['Central District']).map(u=><option key={u}>{u}</option>)}</select></label><details className="factor-details"><summary>Second-factor code <span>Optional</span></summary><label>Verification code<input value={factor} onChange={e=>setFactor(e.target.value)} placeholder="Not configured in this demo" maxLength={12}/></label><small>Second-factor authentication requires an identity-provider integration.</small></details><button className="primary signin-submit" disabled={busy}>{busy?'Signing in…':'Sign in to command centre'}<ArrowRight size={17}/></button></form><p className="authorized"><ShieldCheck size={14}/>Demo build. No credentials are validated.</p>{config?.demo&&<details className="demo-access"><summary><span>Demo access</span><ChevronDown size={15}/></summary><p>Synthetic data only. Choose a role to fill demo credentials.</p><div className="demo-role-buttons">{config.demo_users.map(u=><button key={u.username} type="button" onClick={()=>{setUsername(u.username);setPassword(u.password);setError('');}}>Use {u.role}</button>)}</div><small>Password: <code>demo</code></small></details>}<div className="signin-bottom"><span className="status-dot"/>Local processing <span>·</span> Synthetic Delhi dataset <span>·</span> v2.0</div></motion.div></section></div>;
}
