import { useEffect, useMemo, useState } from 'react';
import { Pause, Play, Download } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Badge, Page, PageHeader, Panel } from '../components/UI';
import NetworkMap from '../components/NetworkMap';
import { cameras, cameraById, roads, densityAt, corridorsAt, hourly, vehicles, reads } from '../demo/model';
import { useDemo } from '../demo/context';
import { REGIONS } from '../constants/city';
import { download } from './Trajectory';

export default function Traffic(){const {region,setRegion}=useDemo(),[hour,setHour]=useState(9),[day,setDay]=useState(30),[playing,setPlaying]=useState(false),[tab,setTab]=useState('Density heatmap');
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>{if(!document.hidden)setHour(h=>(h+1)%24);},1100);return()=>clearInterval(timer);},[playing]);
 const density=useMemo(()=>densityAt(hour,region,day),[hour,region,day]),corridors=useMemo(()=>corridorsAt(hour),[hour]),scopedCorridors=corridors.filter(r=>region==='All Delhi'||cameraById.get(r.from)?.region===region||cameraById.get(r.to)?.region===region),sum=density.reduce((s,d)=>s+d.count,0),speed=Math.round(scopedCorridors.reduce((s,c)=>s+(c.median_speed_kmh||0),0)/Math.max(1,scopedCorridors.length)),hotspots=[...density].sort((a,b)=>b.count-a.count).slice(0,12);
 const od=useMemo(()=>{const trips=vehicles.flatMap(v=>{const own=reads.filter(r=>r.identity_id===v.id);const days=[...new Set(own.map(r=>r.timestamp.slice(0,10)))];return days.map(d=>{const daily=own.filter(r=>r.timestamp.startsWith(d));return {from:daily[0].camera_id,to:daily.at(-1)!.camera_id,count:1};});});const matrix=REGIONS.map(from=>({from,values:REGIONS.map(to=>trips.filter(t=>cameraById.get(t.from)?.region===from&&cameraById.get(t.to)?.region===to).length)}));return {trips,matrix};},[]);
 const flow=od.trips.filter(f=>region==='All Delhi'||cameraById.get(f.from)?.region===region||cameraById.get(f.to)?.region===region).slice(0,45);
 const trend=Array.from({length:24},(_,h)=>({hour:`${String(h).padStart(2,'0')}:00`,volume:densityAt(h,region,day).reduce((s,d)=>s+d.count,0),previous:densityAt(h,region,Math.max(1,day-1)).reduce((s,d)=>s+d.count,0)}));
 return <Page><PageHeader title="Delhi traffic intelligence" description="Explore simulated density, corridor speeds and regional movement across the entire city." actions={<Badge tone="amber">Seeded traffic model · September 2026</Badge>}/><div className="tabs" role="tablist">{['Density heatmap','Origin–Destination','Congestion hotspots','Trends'].map(t=><button key={t} role="tab" aria-selected={t===tab} className={t===tab?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 <div className="filter-bar standalone"><label>Operational region<select aria-label="Traffic region" value={region} onChange={e=>setRegion(e.target.value)}><option>All Delhi</option>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></label><label>Demo date<select aria-label="Heatmap date" value={day} onChange={e=>setDay(+e.target.value)}>{Array.from({length:30},(_,i)=><option key={i} value={i+1}>{i+1} September 2026</option>)}</select></label><span className="muted">{density.length} cameras in scope</span><button onClick={()=>download('delhi-traffic.csv','\ufeffRegion,Camera,Day,Hour,Simulated passes\r\n'+density.map(d=>`${region},${d.name},2026-09-${day},${hour},${d.count}`).join('\r\n'),'text/csv;charset=utf-8')}><Download size={14}/>Export CSV</button></div>
 <div className="journey-stats"><div><small>Selected hour · IST</small><strong>{String(hour).padStart(2,'0')}:00–{String((hour+1)%24).padStart(2,'0')}:00</strong></div><div><small>Simulated vehicle passes</small><strong>{sum.toLocaleString('en-IN')}</strong></div><div><small>Mean corridor speed</small><strong>{speed} km/h</strong></div><div><small>Slow corridors (&lt; 18 km/h)</small><strong>{scopedCorridors.filter(c=>(c.median_speed_kmh||0)<18).length}</strong></div></div>
 {tab!=='Trends'&&<div className="traffic-layout"><Panel title={tab==='Origin–Destination'?'Regional flow map':'Delhi density & speed map'} subtitle="Warm colour = more passes · road colour = modeled speed"><NetworkMap key={tab} cameras={cameras} roads={roads} corridors={corridors} density={density} region={region} onRegion={setRegion} heat={tab!=='Origin–Destination'} flows={tab==='Origin–Destination'?flow:[]} large/><div className="heat-playback"><button className="primary" onClick={()=>setPlaying(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause time-lapse':'Play time-lapse'}</button><label>Hour of day · {String(hour).padStart(2,'0')}:00 IST<input aria-label="Heatmap hour" type="range" min="0" max="23" value={hour} onChange={e=>{setPlaying(false);setHour(+e.target.value);}}/></label><span className="heat-scale">Low <i/> High</span></div><div className="map-legend"><span><i className="free"/>Free &gt;38 km/h</span><span><i className="moderate"/>Moderate</span><span><i className="heavy"/>Heavy</span><span><i className="congested"/>Congested &lt;18 km/h</span></div></Panel><Panel title="Congestion hotspots" subtitle={`${region} · ranked by simulated hourly passes`}><div className="hotspot-list">{hotspots.map((d,i)=><button key={d.camera_id} onClick={()=>setRegion(cameraById.get(d.camera_id)!.region)}><b>{String(i+1).padStart(2,'0')}</b><div><strong>{d.name}</strong><small>{cameraById.get(d.camera_id)?.region}</small><span className="hotspot-bar"><i style={{width:`${d.count/Math.max(1,hotspots[0].count)*100}%`}}/></span></div><span>{d.count}<small>passes/h</small><Badge tone={d.count>180?'red':d.count>100?'amber':'green'}>{d.count>180?'Heavy':d.count>100?'Moderate':'Free'}</Badge></span></button>)}</div></Panel></div>}
 {tab==='Origin–Destination'&&<Panel title="Origin–Destination matrix" subtitle="Trips from seeded daily first and last observations · seven-day dataset" className="mt-panel"><div className="table-scroll"><table className="od-matrix"><thead><tr><th>From / To</th>{REGIONS.map(r=><th key={r}>{r.replace(' Delhi','')}</th>)}</tr></thead><tbody>{od.matrix.filter(row=>region==='All Delhi'||row.from===region).map(row=><tr key={row.from}><th>{row.from}</th>{row.values.map((n,i)=><td key={i} style={{background:n?'var(--accent-bg)':undefined}}>{n||'—'}</td>)}</tr>)}</tbody></table></div></Panel>}
 {tab==='Congestion hotspots'&&<Panel title="Corridor detail" subtitle="Modeled traffic performance, not sensor measurements" className="mt-panel"><div className="table-scroll"><table><thead><tr><th>Corridor</th><th>Speed</th><th>Traffic level</th><th>Modeled queue duration</th></tr></thead><tbody>{[...scopedCorridors].sort((a,b)=>(a.median_speed_kmh||0)-(b.median_speed_kmh||0)).slice(0,12).map(c=><tr key={c.from+c.to}><td>{cameraById.get(c.from)?.name} → {cameraById.get(c.to)?.name}</td><td>{c.median_speed_kmh} km/h</td><td>{c.level}</td><td>{Math.max(0,50-(c.median_speed_kmh||0))} minutes</td></tr>)}</tbody></table></div></Panel>}
 {tab==='Trends'&&<><Panel title="Hourly traffic volume" subtitle="Selected day versus previous day · deterministic simulated counts"><div className="traffic-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="hour" stroke="var(--muted)" fontSize={10}/><YAxis stroke="var(--muted)" fontSize={10}/><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--border)',color:'var(--text)'}}/><Area type="monotone" dataKey="previous" name="Previous day" stroke="var(--route-b)" fill="var(--route-b)" fillOpacity={.08}/><Area type="monotone" dataKey="volume" name="Selected day" stroke="var(--green)" fill="var(--green)" fillOpacity={.2}/></AreaChart></ResponsiveContainer></div></Panel><div className="two-columns mt-panel"><Panel title="Peak-hour analysis"><div className="padded"><h3>Morning 08:00–10:00 · evening 17:00–20:00 IST</h3><p className="muted mt-panel">The modeled evening peak reaches {Math.max(...trend.map(t=>t.volume)).toLocaleString()} passes/hour in {region}. These counts come from a seeded traffic model, separate from the searchable plate records.</p><p className="muted mt-panel">{hourly.length} city-wide hourly buckets across 30 days.</p></div></Panel><Panel title="Simulated short-term forecast"><div className="padded">{[15,30,60].map(m=><div className="stat-pair" key={m}><span>Next {m} minutes · ±15% model band</span><strong>{Math.round(sum*(1+m/400))} passes/h</strong></div>)}<Badge tone="amber">Illustrative forecast · not a trained prediction</Badge></div></Panel></div></>}
 </Page>;
}
