import {useEffect,useState} from 'react';
import {Panel} from '../../components/UI';
import NetworkMap from '../../components/NetworkMap';
import {cameras,roads} from '../../demo/model';
import {ProvenanceChip} from '../../lib/provenance';
import {useSession} from '../../session';
import Evidence from '../LiveOCRRun/Evidence';
import {caseGeoJSON,mapTrajectory,plateText,type LiveCase} from './LiveCaseStore';

export default function LiveCaseJourney({value:c}:{value:LiveCase}){
 const {session}=useSession(),authorised=!!session&&session.user.role!=='viewer';
 const [progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>{if(!document.hidden)setProgress(p=>Math.min(1,p+speed/240));},100);return()=>clearInterval(id);},[playing,speed]);
 useEffect(()=>{if(progress>=1)setPlaying(false);},[progress]);
 const index=Math.min(c.stops.length-1,Math.floor(progress*Math.max(1,c.stops.length-1))),active=c.stops[index],trajectory=mapTrajectory(c,authorised);
 function exportCase(){const url=URL.createObjectURL(new Blob([JSON.stringify(caseGeoJSON(c,authorised),null,2)],{type:'application/geo+json'})),a=document.createElement('a');a.href=url;a.download=`live-case-${c.id}.geojson`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="live-case-journey"><Panel title={`Test case · ${plateText(c.plate,authorised)}`}><div className="padded"><div className="flex gap-2">{c.generated&&<ProvenanceChip source="generated"/>}{c.staged&&<ProvenanceChip source="staged"/>}<ProvenanceChip source="live"/></div><p>{c.stops.length} sightings · {c.total_distance_km.toFixed(3)} km · {c.stops.some(s=>s.implausible)?'Impossible-travel flag':'Plausible travel'} · Purpose: {c.purpose}</p>{c.stops.length===1&&<p>One sighting: a trajectory needs at least two</p>}<p>Same plate across clips; vehicle identity still requires review. Dwell: not measured. Track spans measure visibility, not stationary time.</p><button onClick={exportCase}>Export case GeoJSON</button><button onClick={()=>window.print()}>Print case file</button></div></Panel><div className="trajectory-layout"><Panel title="Test-case journey map"><NetworkMap cameras={cameras} roads={roads} trajectory={trajectory} progress={progress} large/><div className="playback"><button onClick={()=>{if(progress>=1)setProgress(0);setPlaying(!playing);}}>{playing?'Pause':'Replay journey'}</button><input aria-label="Test-case journey position" type="range" min="0" max="1" step=".001" value={progress} onChange={e=>{setPlaying(false);setProgress(+e.target.value);}}/><select aria-label="Test-case playback speed" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[1,2,4,8].map(n=><option key={n} value={n}>{n}×</option>)}</select></div></Panel><Panel title="Test-case stops"><div className="journey-timeline">{c.stops.map((s,i)=><section key={`${s.clip}-${s.track_id}`} className={`timeline-stop ${index===i?'active':''}`}><button onClick={()=>{setPlaying(false);setProgress(i/Math.max(1,c.stops.length-1));}}>Stop {i+1} · {s.camera.name}</button><p>{s.ts_ist} · {s.camera_id}</p><p>{plateText(c.plate,authorised)} · {(s.vote_confidence*100).toFixed(1)}% vote confidence · {s.leg_distance_km.toFixed(3)} km · {s.speed_kmh==null?'First sighting':`${s.speed_kmh} km/h`} · {s.implausible?'Impossible-travel flag':'Plausible'}</p>{s.generated&&<ProvenanceChip source="generated"/>}{s.staged&&<ProvenanceChip source="staged"/>}<p>Computed from file: <code className="file-hash">{s.sha256}</code></p><small>Visible track span: {s.observed_span_s?.toFixed(2)??'Not measured'} s</small></section>)}</div></Panel></div>{active&&<Panel title={`Stop evidence · ${active.camera.name}`}><div className="padded">{active.generated&&<ProvenanceChip source="generated"/>}{active.staged&&<ProvenanceChip source="staged"/>}<p>{active.clip} · first tracked appearance {active.video_time_s.toFixed(2)}s. The detection box is shown only at its measured evidence frame.</p>{authorised?<Evidence key={`${c.id}-${index}`} upload={c.uploads?.find(u=>u.file.name===active.clip)} plate={active.evidence} seek={active.video_time_s}/>:<p>Plate masked. Officer access required for video evidence.</p>}</div></Panel>}</section>;
}
