import RealProfile from './real/RealSearch';
import { RealFootageProvider } from './real/context';
import Privacy from './real/Privacy';
import './real/real.css';
import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { NavLink, Navigate, Route, Routes, useLocation, useNavigate } from './router';
import { Activity, Bell, BookOpen, Camera, ChevronDown, ChevronRight, Clapperboard, Command, Fingerprint, LayoutDashboard, LogOut, Map, Menu, Moon, Route as RouteIcon, ScanText, Search, Settings2, ShieldAlert, ShieldCheck, Sun, X } from 'lucide-react';
import { AnimatePresence, MotionConfig } from 'framer-motion';
import { useSession } from './session';
import { DataProvider, useData } from './data';
import { Badge, Empty, ErrorMessage, Loading, Logo, Panel } from './components/UI';
import SignIn from './pages/SignIn';
import Overview from './pages/Overview';
import SearchPage from './pages/Search';
import { DemoProvider, useDemo } from './demo/context';
import { REGIONS } from './constants/city';
const Trajectories=lazy(()=>import('./pages/Trajectory'));
const Analytics=lazy(()=>import('./pages/Traffic'));
const Attributes=lazy(()=>import('./pages/Attributes'));
const Live=lazy(()=>import('./pages/Live'));
const Profile=lazy(()=>import('./pages/Profile'));
const Video=lazy(()=>import('./pages/Video'));
const Intelligence=()=>import('./pages/Intelligence');
const MapPage=lazy(()=>Intelligence().then(m=>({default:m.MapPage}))),Alerts=lazy(()=>Intelligence().then(m=>({default:m.AlertsPage}))),Watchlist=lazy(()=>Intelligence().then(m=>({default:m.WatchlistPage}))),OCR=lazy(()=>Intelligence().then(m=>({default:m.OCRPage}))),Audit=lazy(()=>Intelligence().then(m=>({default:m.AuditPage}))),Admin=lazy(()=>Intelligence().then(m=>({default:m.Administration})));

const links=[{path:'/',label:'Overview',icon:LayoutDashboard,group:'WORKSPACE'}, {path:'/live',label:'Live monitoring',icon:Camera},{path:'/wall',label:'Control room wall',icon:LayoutDashboard},{path:'/map',label:'Delhi map',icon:Map},{path:'/search',label:'Vehicle search',icon:Search,officer:true},{path:'/attributes',label:'Attribute search',icon:Fingerprint,officer:true},{path:'/video',label:'Video analysis',icon:Clapperboard,officer:true},{path:'/trajectories',label:'Plate trajectory',icon:RouteIcon,officer:true},{path:'/analytics',label:'Density & analytics',icon:Activity,group:'INTELLIGENCE'},{path:'/alerts',label:'Alerts',icon:ShieldAlert,officer:true},{path:'/watchlist',label:'Watchlist',icon:ShieldCheck,officer:true},{path:'/ocr',label:'OCR Lab',icon:ScanText,officer:true},{path:'/audit',label:'Audit log',icon:BookOpen,admin:true,group:'SYSTEM'},{path:'/privacy',label:'Privacy & DPDP',icon:ShieldCheck,admin:true},{path:'/admin',label:'Administration',icon:Settings2,admin:true}];
function Guard({admin=false,children}:{admin?:boolean;children:ReactNode}){const {session}=useSession();return (admin?session?.user.role==='admin':session?.user.role!=='viewer')?<>{children}</>:<Panel><Empty title="Restricted workspace" message={`This area requires ${admin?'Admin':'Officer'} access. Your current role can view traffic analytics and the camera network.`}/></Panel>;}
function Shell(){const demo=useDemo(),{session,logout,renew,expiresAt,config}=useSession(),d=useData(),navigate=useNavigate(),location=useLocation(),searchRef=useRef<HTMLInputElement>(null);const [query,setQuery]=useState(''),[theme,setTheme]=useState('light'),[mobile,setMobile]=useState(false),[now,setNow]=useState(Date.now()),[error,setError]=useState('');const user=session!.user;
  useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);
  useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchRef.current?.focus();}if(e.key==='Escape')setMobile(false);};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);
  useEffect(()=>{setMobile(false);window.scrollTo(0,0);},[location.pathname]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
  const current=links.find(l=>l.path===location.pathname)?.label||'Vehicle profile',openAlerts=d.alerts.filter(a=>a.status!=='Closed').length,remaining=Math.max(0,Math.ceil((expiresAt-now)/1000));
  return <div className="app-shell"><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus();}}>Skip to content</a>{mobile&&<button className="sidebar-backdrop" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}<aside className={`sidebar ${mobile?'is-open':''}`}><div className="sidebar-brand"><Logo/><p>City ANPR Trajectory<br/>& Traffic Intelligence</p><button className="mobile-close" onClick={()=>setMobile(false)} aria-label="Close navigation"><X size={19}/></button></div><div className="unit-card"><span className="unit-avatar"><Camera size={16}/></span><div><strong>Delhi command</strong><small>{user.unit}</small></div><ChevronDown size={14}/></div><nav aria-label="Main navigation">{links.filter(l=>!l.admin||user.role==='admin').map(l=><div key={l.path}>{l.group&&<div className="nav-group">{l.group}</div>}<NavLink to={l.path} end={l.path==='/'} className={({isActive})=>`${isActive?'active':''} ${l.officer&&user.role==='viewer'?'restricted-nav':''}`}><l.icon size={17}/><span>{l.label}</span>{l.path==='/alerts'&&openAlerts>0&&<b className="nav-count">{openAlerts}</b>}{l.path==='/'&&<span className="nav-active-dot"/>}</NavLink></div>)}</nav><div className="sidebar-bottom"><div className="evidence-status"><ShieldCheck size={18}/><div><strong>Demo pipeline</strong><small>OCR & tracking · simulated</small></div></div><span>SIH 2026 <i/> SIH26127 <Badge>DEMO v2.0</Badge></span></div></aside>
  <div className="app-main"><header className="topbar"><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={20}/></button><div className="breadcrumb">Workspace <ChevronRight size={13}/><strong>{current}</strong></div><form className="global-search" onSubmit={e=>{e.preventDefault();navigate(`/search?q=${encodeURIComponent(query)}`);}}><Search size={16}/><input ref={searchRef} placeholder="Search a registration…" aria-label="Global plate search" value={query} onChange={e=>setQuery(e.target.value)} disabled={user.role==='viewer'}/><kbd><Command size={11}/> K</kbd></form><div className="topbar-actions"><Badge tone="blue">{config?.demo?'Demo data':'Gateway mode'}</Badge><button className="icon-button" title={theme==='dark'?'Switch to light theme':'Switch to dark theme'} aria-label="Toggle theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><button className="notification-button icon-button" aria-label={`${openAlerts} alerts for review`} onClick={()=>navigate('/alerts')}><Bell size={17}/>{openAlerts>0&&<span>{openAlerts}</span>}</button><div className="user-menu"><span className="avatar">{user.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><strong>{user.name}</strong><small>{user.role} · {user.unit}</small></div><button className="icon-button" title="Sign out" aria-label="Sign out" onClick={()=>void logout()}><LogOut size={15}/></button></div></div></header>
  <main id="main-content" tabIndex={-1}><div className="workspace-status"><span><span className="status-dot"/>{d.error?'Connection requires attention':d.connected?'Demo workspace ready':'Local workspace'}<span className="status-separator">|</span>Simulated Delhi data · resets on reload</span><time>{new Date(now).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})} <span className="status-separator">/</span> {new Date(now).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour12:false})} IST</time></div>{remaining<120&&<div className="session-warning" role="alert">Your session expires in {remaining}s.<button onClick={()=>void renew().catch(e=>setError(e.message))}>Extend session</button></div>}{error&&<ErrorMessage message={error}/>}<div className="demo-command-bar"><label>Scope<select aria-label="Workspace region" value={demo.region} onChange={e=>demo.setRegion(e.target.value)}><option>All Delhi</option>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></label><span>Demo period: 24–30 Sep 2026</span><button className="primary" onClick={demo.running?demo.stop:demo.start}>{demo.running?`Stop scenario · ${demo.elapsed}s`:'Run demo scenario'}</button><button onClick={demo.reset}>Reset scenario</button></div>{demo.notice&&<div className="demo-notice" role="status">{demo.notice}</div>}<AnimatePresence mode="wait"><Suspense fallback={<Loading label="Loading workspace…"/>}><Routes location={location} key={location.pathname}><Route path="/" element={<Overview/>}/><Route path="/live" element={<Live/>}/><Route path="/wall" element={<Live wall/>}/><Route path="/map" element={<MapPage/>}/><Route path="/analytics" element={<Analytics/>}/><Route path="/search" element={<Guard><SearchPage/></Guard>}/><Route path="/real-vehicles/:id" element={<Guard><RealProfile/></Guard>}/><Route path="/vehicles/:id" element={<Guard><Profile/></Guard>}/><Route path="/attributes" element={<Guard><Attributes/></Guard>}/><Route path="/video" element={<Guard><Video/></Guard>}/><Route path="/trajectories" element={<Guard><Trajectories/></Guard>}/><Route path="/alerts" element={<Guard><Alerts/></Guard>}/><Route path="/watchlist" element={<Guard><Watchlist/></Guard>}/><Route path="/ocr" element={<Guard><OCR/></Guard>}/><Route path="/audit" element={<Guard admin><Audit/></Guard>}/><Route path="/privacy" element={<Guard admin><Privacy/></Guard>}/><Route path="/admin" element={<Guard admin><Admin/></Guard>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Suspense></AnimatePresence><footer className="workspace-footer"><span>CityTrace · City-wide intelligence, grounded in evidence.</span><span>SIH26127 <span className="separator">/</span> Prototype · Human review required</span></footer></main></div></div>;
}
export default function App(){const {session,initializing}=useSession();return <MotionConfig reducedMotion="user">{initializing?<div className="boot-screen"><Logo/><Loading label="Connecting to CityTrace…"/></div>:session?<DataProvider key={session.user.username}><DemoProvider><RealFootageProvider><Shell/></RealFootageProvider></DemoProvider></DataProvider>:<SignIn/>}</MotionConfig>;}

